FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci --no-audit --no-fund

FROM base AS build
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
# 크레딧 식별자 빌드 시 주입 (미전달 시 i18n.ts의 공개 fallback 사용).
# 사내 배포는 CI가 GitHub Actions secret에서 --build-arg로 넘김.
ARG NEXT_PUBLIC_CREDIT_ORG
ARG NEXT_PUBLIC_CREDIT_AUTHOR
ARG NEXT_PUBLIC_CREDIT_AUTHOR_URL
ENV NEXT_PUBLIC_CREDIT_ORG=$NEXT_PUBLIC_CREDIT_ORG
ENV NEXT_PUBLIC_CREDIT_AUTHOR=$NEXT_PUBLIC_CREDIT_AUTHOR
ENV NEXT_PUBLIC_CREDIT_AUTHOR_URL=$NEXT_PUBLIC_CREDIT_AUTHOR_URL
# 공개 서비스 설정 — 광고/사이트URL/분석. NEXT_PUBLIC_* 이라 빌드 시 정적 치환되므로
# 런타임 secret이 아닌 build-arg로 주입해야 함. 미전달 시 각 모듈의 공개 fallback(none/localhost).
ARG NEXT_PUBLIC_AD_NETWORK
ARG NEXT_PUBLIC_ADFIT_UNIT_LOBBY
ARG NEXT_PUBLIC_ADFIT_UNIT_RESULT
ARG NEXT_PUBLIC_ADFIT_UNIT_LANDING
ARG NEXT_PUBLIC_ADSENSE_CLIENT
ARG NEXT_PUBLIC_ADSENSE_SLOT_LOBBY
ARG NEXT_PUBLIC_ADSENSE_SLOT_RESULT
ARG NEXT_PUBLIC_ADSENSE_SLOT_LANDING
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_ANALYTICS_PROVIDER
ARG NEXT_PUBLIC_CF_BEACON_TOKEN
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_AD_NETWORK=$NEXT_PUBLIC_AD_NETWORK
ENV NEXT_PUBLIC_ADFIT_UNIT_LOBBY=$NEXT_PUBLIC_ADFIT_UNIT_LOBBY
ENV NEXT_PUBLIC_ADFIT_UNIT_RESULT=$NEXT_PUBLIC_ADFIT_UNIT_RESULT
ENV NEXT_PUBLIC_ADFIT_UNIT_LANDING=$NEXT_PUBLIC_ADFIT_UNIT_LANDING
ENV NEXT_PUBLIC_ADSENSE_CLIENT=$NEXT_PUBLIC_ADSENSE_CLIENT
ENV NEXT_PUBLIC_ADSENSE_SLOT_LOBBY=$NEXT_PUBLIC_ADSENSE_SLOT_LOBBY
ENV NEXT_PUBLIC_ADSENSE_SLOT_RESULT=$NEXT_PUBLIC_ADSENSE_SLOT_RESULT
ENV NEXT_PUBLIC_ADSENSE_SLOT_LANDING=$NEXT_PUBLIC_ADSENSE_SLOT_LANDING
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_ANALYTICS_PROVIDER=$NEXT_PUBLIC_ANALYTICS_PROVIDER
ENV NEXT_PUBLIC_CF_BEACON_TOKEN=$NEXT_PUBLIC_CF_BEACON_TOKEN
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/server.ts ./server.ts
COPY --from=build /app/next.config.js ./next.config.js
COPY --from=build /app/tsconfig.json ./tsconfig.json
COPY --from=build /app/src ./src
COPY --from=build /app/public ./public
EXPOSE 3000
CMD ["npm", "start"]
