// 넌센스 퀴즈 문제 풀. 한국어 전용. 가볍고 누구나 웃는 파티 톤 — 말장난·언어유희와
// 재치/상황추론(엉뚱한 논리)을 섞는다. 정치·종교·민감 주제 제외. trivia와 동일 스키마라
// trivia 엔진(buildQuizPlan/computeQuizResult)이 그대로 채점·재생한다.
//
// 문항 추가: 배열 끝에 append하고 새 id(kebab-case)만 부여. 기존 순서 바꾸지 말 것 —
// 서버가 seed 기반으로 섞고, 풀 자체는 런타임에 id 사전순(NONSENSE_POOL_SORTED)으로
// 정렬한 뒤 추출하므로 삽입 순서는 결정성에 영향 없음.
//
// 카피 규칙: question ~40자, choices 각 ~10자(모바일 한 줄). 정답 외 3개는 그럴싸한 함정.

export type NonsenseCategory = '말장난' | '재치' | '상황추론';

export type NonsenseQuestion = {
  id: string;
  category: NonsenseCategory;
  question: string;
  choices: readonly [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  /** 정답 공개 화면에 뜨는 한 줄 해설. ≤80자. 답이 자명하면 생략. */
  note?: string;
};

export const NONSENSE_POOL: readonly NonsenseQuestion[] = [
  // ── 말장난 ────────────────────────────────────────────────────
  {
    id: 'pun-king-fall',
    category: '말장난',
    question: '왕이 넘어지면?',
    choices: ['임금님', '킹콩', '왕쾅', '폭삭'],
    correctIndex: 1,
    note: "킹(king)이 '콩' 하고 넘어졌으니 킹콩.",
  },
  {
    id: 'pun-fast-chicken',
    category: '말장난',
    question: '세상에서 가장 빠른 닭은?',
    choices: ['번개닭', '후다닭', '제트닭', '총알닭'],
    correctIndex: 1,
    note: "'후다닥' + 닭.",
  },
  {
    id: 'pun-cold-sea',
    category: '말장난',
    question: '세상에서 가장 추운 바다는?',
    choices: ['북극해', '동해', '썰렁해', '냉해'],
    correctIndex: 2,
    note: '썰렁해~',
  },
  {
    id: 'pun-two-foot-cow',
    category: '말장난',
    question: '발이 두 개 달린 소는?',
    choices: ['정육점', '외양간', '이발소', '목장'],
    correctIndex: 2,
    note: '이(2)발 + 소 = 이발소.',
  },
  {
    id: 'pun-kind-lion',
    category: '말장난',
    question: '세상에서 가장 친절한 사자는?',
    choices: ['의사', '자원봉사자', '변호사', '요리사'],
    correctIndex: 1,
    note: "봉사 + '자'로 끝나는 사자(者).",
  },
  {
    id: 'pun-thief-icecream',
    category: '말장난',
    question: '도둑이 가장 무서워하는 아이스크림은?',
    choices: ['월드콘', '스크류바', '누가바', '빵빠레'],
    correctIndex: 2,
    note: "'누가 봐?'",
  },
  {
    id: 'pun-hot-fruit',
    category: '말장난',
    question: '세상에서 가장 뜨거운 과일은?',
    choices: ['한라봉', '천도복숭아', '파인애플', '용과'],
    correctIndex: 1,
    note: '천도(1000도) 복숭아.',
  },
  {
    id: 'pun-high-chief',
    category: '말장난',
    question: '추장보다 높은 사람은?',
    choices: ['부족장', '고추장', '대추장', '면장'],
    correctIndex: 1,
    note: '고(高) + 추장.',
  },
  {
    id: 'pun-dirty-river',
    category: '말장난',
    question: '세상에서 가장 더러운 강은?',
    choices: ['한강', '낙동강', '요강', '압록강'],
    correctIndex: 2,
    note: '요강(옛날 실내 변기).',
  },
  {
    id: 'pun-laughing-cow',
    category: '말장난',
    question: '소가 크게 웃으면?',
    choices: ['음매', '우하하', '깔깔', '메에'],
    correctIndex: 1,
    note: '소 우(牛) + 하하.',
  },
  {
    id: 'pun-burger-color',
    category: '말장난',
    question: '물고기의 반대말은?',
    choices: ['붕어', '불고기', '생선', '잉어'],
    correctIndex: 1,
    note: '물고기의 \'물\'을 \'불\'로 바꾼 불고기 말장난.',
  },
  {
    id: 'pun-dad-lost',
    category: '말장난',
    question: '아빠가 길을 잃으면?',
    choices: ['길치', '파파라치', '마마보이', '미아'],
    correctIndex: 1,
    note: '파파(아빠) + 라치.',
  },

  // ── 재치 ─────────────────────────────────────────────────────
  {
    id: 'wit-months-28',
    category: '재치',
    question: '28일이 있는 달은 1년에 몇 개?',
    choices: ['1개', '2개', '4개', '12개'],
    correctIndex: 3,
    note: '모든 달이 최소 28일은 있다.',
  },
  {
    id: 'wit-cotton-iron',
    category: '재치',
    question: '1kg의 솜과 1kg의 쇠, 더 무거운 것은?',
    choices: ['솜', '쇠', '똑같다', '알 수 없음'],
    correctIndex: 2,
    note: '둘 다 1kg.',
  },
  {
    id: 'wit-alphabet-letters',
    category: '재치',
    question: "'알파벳'에는 글자가 몇 개 들어 있을까?",
    choices: ['26개', '3개', '24개', '알 수 없음'],
    correctIndex: 1,
    note: "단어 '알·파·벳' 세 글자.",
  },
  {
    id: 'wit-right-hand',
    category: '재치',
    question: '오른손으로 절대 만질 수 없는 것은?',
    choices: ['왼손', '오른팔', '오른손', '오른발'],
    correctIndex: 2,
    note: '오른손은 자기 자신을 잡을 수 없다.',
  },
  {
    id: 'wit-race-overtake',
    category: '재치',
    question: '달리기에서 2등을 제치면 몇 등?',
    choices: ['1등', '2등', '3등', '꼴등'],
    correctIndex: 1,
    note: '제친 그 사람 자리(2등)를 차지할 뿐.',
  },
  {
    id: 'wit-candle-blow',
    category: '재치',
    question: '켜둔 양초 10개 중 3개가 바람에 꺼졌다. 다음 날 남은 건?',
    choices: ['7개', '10개', '3개', '0개'],
    correctIndex: 2,
    note: '꺼진 3개만 남고 나머지는 끝까지 타버린다.',
  },
  {
    id: 'wit-what-goes-up',
    category: '재치',
    question: '올라가기만 하고 절대 내려오지 않는 것은?',
    choices: ['연기', '나이', '풍선', '온도'],
    correctIndex: 1,
    note: '나이는 늘기만 한다.',
  },
  {
    id: 'wit-footprints',
    category: '재치',
    question: '가져갈수록 더 많이 남는 것은?',
    choices: ['돈', '발자국', '시간', '그림자'],
    correctIndex: 1,
    note: '걸을수록 발자국이 늘어난다.',
  },
  {
    id: 'wit-never-wither',
    category: '재치',
    question: '물을 주면 죽고, 안 주면 사는 것은?',
    choices: ['선인장', '조화', '불', '이끼'],
    correctIndex: 2,
    note: '불은 물에 꺼진다.',
  },
  {
    id: 'wit-sponge-holes',
    category: '재치',
    question: '구멍이 숭숭 뚫렸는데도 물을 머금는 것은?',
    choices: ['그물', '스펀지', '체', '빨대'],
    correctIndex: 1,
    note: '스펀지는 구멍이 많아도 물을 빨아들인다.',
  },
  {
    id: 'wit-birthday-twice',
    category: '재치',
    question: '한 해에 생일을 두 번 챙기는 사람도 있다. 어떻게?',
    choices: ['거짓말', '쌍둥이', '음력·양력', '윤년생'],
    correctIndex: 2,
    note: '음력 생일과 양력 생일을 둘 다 챙기면.',
  },

  // ── 상황추론 ──────────────────────────────────────────────────
  {
    id: 'logic-sheep-9',
    category: '상황추론',
    question: '양 17마리 중 9마리만 빼고 모두 죽었다. 남은 양은?',
    choices: ['8마리', '9마리', '17마리', '0마리'],
    correctIndex: 1,
    note: "'9마리만 빼고'이므로 그 9마리가 살아남았다.",
  },
  {
    id: 'logic-fire-first',
    category: '상황추론',
    question: '추운 방, 성냥 한 개비로 양초·난로·램프에 불을 붙이려면 뭐부터?',
    choices: ['양초', '난로', '성냥', '램프'],
    correctIndex: 2,
    note: '성냥에 먼저 불을 붙여야 나머지에 옮길 수 있다.',
  },
  {
    id: 'logic-green-house',
    category: '상황추론',
    question: '빨간 집은 빨간 벽돌, 노란 집은 노란 벽돌. 그린하우스는 뭘로 지을까?',
    choices: ['초록 벽돌', '유리', '잔디', '나무'],
    correctIndex: 1,
    note: '그린하우스 = 온실, 유리로 짓는다.',
  },
  {
    id: 'logic-dark-road',
    category: '상황추론',
    question: '불 꺼진 차가 검은 옷 입은 사람을 가로등도 없이 피했다. 어떻게?',
    choices: ['헤드라이트', '가로등', '대낮이라서', '달빛'],
    correctIndex: 2,
    note: '깜깜할 거란 건 착각 — 사실 환한 낮이었다.',
  },
  {
    id: 'logic-frog-well',
    category: '상황추론',
    question: '우물 속 개구리가 낮에 3m 오르고 밤에 2m 미끄러진다. 10m 탈출은?',
    choices: ['10일', '8일', '5일', '9일'],
    correctIndex: 1,
    note: '하루 1m씩, 8일째 낮에 3m 올라 한 번에 빠져나온다.',
  },
  {
    id: 'logic-three-gen-apple',
    category: '상황추론',
    question: '두 아버지와 두 아들이 사과를 하나씩 나눴는데 3개면 충분했다. 왜?',
    choices: ['반씩 잘라서', '세 사람뿐이라서', '한 명이 양보', '사실 4개'],
    correctIndex: 1,
    note: '할아버지·아버지·아들 3대 = 아버지 2명·아들 2명.',
  },
  {
    id: 'logic-doctor-mother',
    category: '상황추론',
    question: '의사가 "저 환자는 내 아들"이라는데 의사는 그 아이의 아버지가 아니다. 누구?',
    choices: ['삼촌', '어머니', '새아빠', '형'],
    correctIndex: 1,
    note: '의사는 그 아이의 어머니.',
  },

  // ── 확장 문제 풀 (말장난·재치·상황추론) ──────────────────────────
  {
    id: 'pun-a-ant-house-address',
    category: '말장난',
    question: '개미네 집 주소는?',
    choices: ['허리도', '다리도', '머리도', '꼬리도'],
    correctIndex: 0,
    note: '개미 허리가 가늘어서 \'허리도 가늘군\'을 주소처럼 비튼 말장난.',
  },
  {
    id: 'pun-a-thief-cat-gold',
    category: '말장난',
    question: '도둑고양이에게 어울리는 금은?',
    choices: ['백금', '야금야금', '순금', '현금'],
    correctIndex: 1,
    note: '몰래 조금씩 먹는 \'야금야금\'을 금 이름처럼 말장난.',
  },
  {
    id: 'pun-a-iron-food',
    category: '말장난',
    question: '다리미가 좋아하는 음식은?',
    choices: ['국수', '피자', '만두', '떡볶이'],
    correctIndex: 1,
    note: '옷을 쭉쭉 \'펴-자\'와 피자의 발음 말장난.',
  },
  {
    id: 'pun-a-titanic-boat',
    category: '말장난',
    question: '구명보트엔 몇 명 탈까?',
    choices: ['7명', '8명', '9명', '10명'],
    correctIndex: 2,
    note: '\'구명\'에 숫자 \'9명\'이 숨어 있는 말장난.',
  },
  {
    id: 'pun-a-cucumber-shock',
    category: '말장난',
    question: '오이가 깜짝 놀라면?',
    choices: ['오이무침', '오마이갓', '오이지', '오이소박이'],
    correctIndex: 1,
    note: '\'오이\'와 영어 \'Oh my\'를 엮은 발음 말장난.',
  },
  {
    id: 'pun-a-pig-laugh',
    category: '말장난',
    question: '돼지가 가장 좋아하는 음악은?',
    choices: ['꿀꿀송', '발라드', '트로트', '힙합'],
    correctIndex: 0,
    note: '돼지 울음 \'꿀꿀\'을 노래 제목처럼 말장난.',
  },
  {
    id: 'pun-a-strawberry-greeting',
    category: '말장난',
    question: '딸기가 직장에서 받는 호칭은?',
    choices: ['딸기씨', '딸기님', '딸기양', '딸기군'],
    correctIndex: 0,
    note: '딸기 속 \'씨(씨앗)\'와 존칭 \'씨\'를 겹친 말장난.',
  },
  {
    id: 'pun-a-cow-money',
    category: '말장난',
    question: '소가 우는 곳은?',
    choices: ['우시장', '소시장', '축사', '외양간'],
    correctIndex: 0,
    note: '소 우는 \'우\'와 시장을 합친 \'우시장\' 말장난.',
  },
  {
    id: 'pun-a-grape-surprise',
    category: '말장난',
    question: '포도가 길에서 넘어지면?',
    choices: ['포도주', '포도알', '아이고', '포도씨'],
    correctIndex: 2,
    note: '넘어질 때 내는 비명 \'아이고\'로 받는 반전 말장난.',
  },
  {
    id: 'pun-a-chicken-school',
    category: '말장난',
    question: '닭이 다니는 학교는?',
    choices: ['꼬꼬학교', '병아리유치원', '닭대학교', '계란고교'],
    correctIndex: 0,
    note: '닭 울음 \'꼬꼬\'를 학교 이름처럼 만든 말장난.',
  },
  {
    id: 'pun-a-bean-anger',
    category: '말장난',
    question: '콩이 화나면 가는 곳은?',
    choices: ['콩밭', '두부공장', '콩나물국', '약콩'],
    correctIndex: 3,
    note: '화나서 \'약 오른다\'와 약콩을 엮은 말장난.',
  },
  {
    id: 'pun-a-radish-laugh',
    category: '말장난',
    question: '무가 크게 웃으면?',
    choices: ['무말랭이', '무하하', '무생채', '무김치'],
    correctIndex: 1,
    note: '\'무\'와 웃음소리 \'하하\'를 붙인 \'무하하\' 말장난.',
  },
  {
    id: 'pun-a-frog-college',
    category: '말장난',
    question: '개구리가 다니는 대학은?',
    choices: ['올챙이대', '개굴대학교', '연못대', '수영대'],
    correctIndex: 1,
    note: '울음소리 \'개굴\'을 대학 이름처럼 만든 말장난.',
  },
  {
    id: 'pun-a-shrimp-back',
    category: '말장난',
    question: '새우가 다니는 병원 과는?',
    choices: ['내과', '정형외과', '안과', '치과'],
    correctIndex: 1,
    note: '등이 굽은 새우라 허리 펴러 가는 정형외과 말장난.',
  },
  {
    id: 'pun-a-bread-greeting',
    category: '말장난',
    question: '빵이 웃으면?',
    choices: ['빵긋', '빵빵', '빵점', '빵야'],
    correctIndex: 0,
    note: '활짝 웃는 \'방긋\'을 \'빵긋\'으로 바꾼 말장난.',
  },
  {
    id: 'pun-a-snake-fast',
    category: '말장난',
    question: '세상에서 가장 무거운 새는?',
    choices: ['독수리', '백조', '타조', '펭귄'],
    correctIndex: 1,
    note: '백조를 숫자 \'100조\'로 읽은 말장난.',
  },
  {
    id: 'pun-a-tofu-fear',
    category: '말장난',
    question: '두부가 가장 무서워하는 건?',
    choices: ['간장', '칼', '된장찌개', '젓가락'],
    correctIndex: 1,
    note: '칼로 잘리는 두부의 운명을 비튼 말장난.',
  },
  {
    id: 'pun-a-bee-school',
    category: '말장난',
    question: '벌이 모여 공부하는 곳은?',
    choices: ['꿀학원', '벌집학교', '윙윙대', '화원'],
    correctIndex: 1,
    note: '벌이 사는 \'벌집\'을 학교 이름처럼 만든 말장난.',
  },
  {
    id: 'pun-a-pumpkin-shock',
    category: '말장난',
    question: '호박이 깜짝 놀라면?',
    choices: ['호박전', '호떡', '호러박', '호박죽'],
    correctIndex: 2,
    note: '\'호박\'에 공포 \'horror\'를 끼운 말장난.',
  },
  {
    id: 'pun-a-fish-test',
    category: '말장난',
    question: '물고기가 시험을 보면?',
    choices: ['붕어빵', '어시험', '비늘점수', '빵점'],
    correctIndex: 3,
    note: '붕어빵처럼 속이 비어 \'빵점\'이라는 말장난.',
  },
  {
    id: 'pun-a-rabbit-fast',
    category: '말장난',
    question: '토끼가 좋아하는 대답은?',
    choices: ['깡총', '빨리나와', '당근이지', '토할것같아'],
    correctIndex: 2,
    note: '\'당연하지\'를 토끼가 좋아하는 \'당근이지\'로 바꾼 말장난.',
  },
  {
    id: 'pun-a-potato-shock',
    category: '말장난',
    question: '세상에서 가장 시끄러운 과일은?',
    choices: ['수박', '방울토마토', '참외', '자두'],
    correctIndex: 1,
    note: '딸랑딸랑 소리 나는 \'방울\'이 든 방울토마토.',
  },
  {
    id: 'pun-a-cat-rich',
    category: '말장난',
    question: '부자 고양이의 인사말은?',
    choices: ['야옹', '돈많아옹', '냐옹', '골골'],
    correctIndex: 1,
    note: '\'돈 많아옹\'을 줄인 부자 고양이 말장난.',
  },
  {
    id: 'pun-a-chestnut-shock',
    category: '말장난',
    question: '밤이 깜짝 놀라면?',
    choices: ['군밤', '밤톨', '아이쿠밤', '밤송이'],
    correctIndex: 2,
    note: '놀라며 외치는 \'아이쿠\'에 밤을 붙인 말장난.',
  },
  {
    id: 'pun-a-tiger-snack',
    category: '말장난',
    question: '호랑이가 좋아하는 과자는?',
    choices: ['새우깡', '어흥깡', '감자깡', '고구마깡'],
    correctIndex: 1,
    note: '호랑이 울음 \'어흥\'에 \'깡\'을 붙인 과자 말장난.',
  },
  {
    id: 'pun-a-lettuce-greeting',
    category: '말장난',
    question: '상추가 가장 좋아하는 말은?',
    choices: ['쌈싸먹자', '쌈박해', '상큼해', '아삭해'],
    correctIndex: 0,
    note: '상추로 쌈 싸 먹는 풍경을 그대로 비튼 말장난.',
  },
  {
    id: 'pun-a-watermelon-shock',
    category: '말장난',
    question: '수박이 깜짝 놀라면?',
    choices: ['수박씨', '박살수박', '수박바', '악수박'],
    correctIndex: 1,
    note: '놀라 \'박살\' 나는 수박을 그린 말장난.',
  },
  {
    id: 'pun-a-clam-quiet',
    category: '말장난',
    question: '가장 입이 무거운 동물은?',
    choices: ['조개', '문어', '거북', '오징어'],
    correctIndex: 0,
    note: '꽉 다문 조개껍데기를 \'입이 무겁다\'로 비튼 말장난.',
  },
  {
    id: 'pun-a-apple-apology',
    category: '말장난',
    question: '사과가 가장 잘하는 것은?',
    choices: ['사과', '변명', '칭찬', '질문'],
    correctIndex: 0,
    note: '과일 사과와 \'미안하다 사과\'의 동음이의 말장난.',
  },
  {
    id: 'pun-a-sheep-yes',
    category: '말장난',
    question: '바나나가 크게 웃으면?',
    choices: ['바나나킥', '바나나칩', '바나나맛', '바나나우유'],
    correctIndex: 0,
    note: '웃다가 \'킥\' 하는 소리를 바나나킥에 빗댄 말장난.',
  },
  {
    id: 'pun-a-horse-tea',
    category: '말장난',
    question: '말이 좋아하는 음료는?',
    choices: ['말차', '당근주스', '사이다', '우유'],
    correctIndex: 0,
    note: '동물 말과 \'말차(가루녹차)\'의 동음 말장난.',
  },
  {
    id: 'pun-a-eggplant-color',
    category: '말장난',
    question: '가지가 부끄러우면?',
    choices: ['가지나물', '보라돌이', '빨개진가지', '가지볶음'],
    correctIndex: 1,
    note: '보라색 가지를 캐릭터 \'보라돌이\'로 비튼 말장난.',
  },
  {
    id: 'pun-a-deer-surprise',
    category: '말장난',
    question: '병아리가 가장 잘 먹는 약은?',
    choices: ['삐약', '소화제', '감기약', '비타민'],
    correctIndex: 0,
    note: '병아리 울음 \'삐악\'을 약에 빗댄 말장난.',
  },
  {
    id: 'pun-a-persimmon-shock',
    category: '말장난',
    question: '감이 갑자기 놀라면?',
    choices: ['곶감', '홍시', '깜짝감', '단감'],
    correctIndex: 2,
    note: '\'깜짝\'에 감을 붙인 \'깜짝감\' 말장난.',
  },
  {
    id: 'pun-a-mouse-game',
    category: '말장난',
    question: '쥐가 잘하는 컴퓨터 작업은?',
    choices: ['클릭', '타이핑', '코딩', '출력'],
    correctIndex: 0,
    note: '동물 쥐와 컴퓨터 \'마우스\'를 엮은 말장난.',
  },
  {
    id: 'pun-a-squid-test',
    category: '말장난',
    question: '오징어가 시험을 망치면?',
    choices: ['오답징어', '먹물뿜기', '마른오징어', '오징어채'],
    correctIndex: 0,
    note: '\'오답\'에 징어를 붙인 \'오답징어\' 말장난.',
  },
  {
    id: 'pun-a-melon-greeting',
    category: '말장난',
    question: '참외가 처음 만나서 하는 말은?',
    choices: ['반가외', '참외씨', '노랗네', '아삭해'],
    correctIndex: 0,
    note: '\'반가워\'를 참외풍으로 \'반가외\'라 한 말장난.',
  },
  {
    id: 'pun-b-baker-city',
    category: '말장난',
    question: '빵집 주인이 제일 무서워하는 도시는?',
    choices: ['로마', '뉴욕', '런던', '파리'],
    correctIndex: 3,
    note: '빵에 곤충 \'파리\'가 꼬이는 것과 도시 파리가 같은 말.',
  },
  {
    id: 'pun-b-doctor-country',
    category: '말장난',
    question: '의사가 제일 좋아하는 나라는?',
    choices: ['인도', '미국', '독일', '태국'],
    correctIndex: 0,
    note: '환자를 \'인도(引導)\'하는 것과 나라 인도가 같은 말.',
  },
  {
    id: 'pun-b-nose-fruit',
    category: '말장난',
    question: '코가 제일 좋아하는 과일은?',
    choices: ['딸기', '수박', '코코넛', '참외'],
    correctIndex: 2,
    note: '\'코\'코넛 첫 글자에 코가 들어가서.',
  },
  {
    id: 'pun-b-eye-vegetable',
    category: '말장난',
    question: '눈이 여러 개 달린 채소는?',
    choices: ['감자', '당근', '양파', '오이'],
    correctIndex: 0,
    note: '감자의 싹 나는 자리를 \'눈\'이라 부르고 여러 개라서.',
  },
  {
    id: 'pun-b-firefighter-city',
    category: '말장난',
    question: '소방관이 제일 싫어하는 도시는?',
    choices: ['부산', '불난', '대구', '광주'],
    correctIndex: 1,
    note: '불이 난 곳 \'불난\'을 도시 이름처럼 비튼 말.',
  },
  {
    id: 'pun-b-pilot-food',
    category: '말장난',
    question: '조종사가 제일 좋아하는 생선은?',
    choices: ['갈치', '고등어', '날치', '참치'],
    correctIndex: 2,
    note: '하늘을 나는 조종사와 \'날아오르는\' 날치가 통해서.',
  },
  {
    id: 'pun-b-farmer-king',
    category: '말장난',
    question: '농부가 가장 존경하는 왕은?',
    choices: ['세종대왕', '파종대왕', '태종', '정조'],
    correctIndex: 1,
    note: '씨를 뿌리는 일 \'파종\'을 대왕 이름처럼 비튼 말.',
  },
  {
    id: 'pun-b-judge-drink',
    category: '말장난',
    question: '판사가 제일 좋아하는 음료는?',
    choices: ['콜라', '사이다', '환타', '식혜'],
    correctIndex: 1,
    note: '속이 시원한 \'사이다\'와 시원한 판결이 통해서.',
  },
  {
    id: 'pun-b-lawyer-fish',
    category: '말장난',
    question: '변호사가 제일 좋아하는 생선은?',
    choices: ['갈치', '대구', '넙치', '참치'],
    correctIndex: 1,
    note: '받아치는 말 \'대구(對句)\'와 생선 대구가 같은 말.',
  },
  {
    id: 'pun-b-diver-fruit',
    category: '말장난',
    question: '잠수부가 좋아할 것 같은 과일은?',
    choices: ['사과', '수박', '잠외', '멜론'],
    correctIndex: 2,
    note: '물에 \'잠\'기는 잠수부와 참외를 합쳐 \'잠외\'로 비튼 말.',
  },
  {
    id: 'pun-b-hand-animal',
    category: '말장난',
    question: '손이 제일 좋아하는 동물은?',
    choices: ['사자', '손오공', '악어', '사슴'],
    correctIndex: 1,
    note: '\'손\'오공 첫 글자에 손이 들어가서.',
  },
  {
    id: 'pun-b-dentist-place',
    category: '말장난',
    question: '치과의사가 제일 좋아하는 동네는?',
    choices: ['이태원', '약수동', '상도동', '송파'],
    correctIndex: 0,
    note: '치아를 뜻하는 \'이\'가 이태원 첫 글자에 들어가서.',
  },
  {
    id: 'pun-b-knee-country',
    category: '말장난',
    question: '개가 학생을 가르치면?',
    choices: ['개인지도', '개훈련', '강아지반', '애견교실'],
    correctIndex: 0,
    note: '\'개\'와 \'개인 지도\'를 엮은 \'개인지도\' 말장난.',
  },
  {
    id: 'pun-b-clock-animal',
    category: '말장난',
    question: '시계가 제일 좋아하는 동물은?',
    choices: ['째깍이', '뻐꾸기', '독수리', '비둘기'],
    correctIndex: 1,
    note: '시간을 알리는 뻐꾸기시계가 있어서.',
  },
  {
    id: 'pun-b-tongue-place',
    category: '말장난',
    question: '혀가 제일 가고 싶어 하는 산은?',
    choices: ['불국산', '해인산', '설악산', '지리산'],
    correctIndex: 2,
    note: '혀를 뜻하는 한자 \'설(舌)\'이 설악산 첫 글자에 들어가서.',
  },
  {
    id: 'pun-b-banker-fruit',
    category: '말장난',
    question: '은행원이 제일 좋아하는 열매는?',
    choices: ['사과', '은행', '바나나', '감'],
    correctIndex: 1,
    note: '돈 다루는 은행과 은행나무 열매 은행이 같은 말.',
  },
  {
    id: 'pun-b-back-place',
    category: '말장난',
    question: '등(背)이 제일 좋아하는 활동은?',
    choices: ['수영', '등산', '낚시', '요가'],
    correctIndex: 1,
    note: '신체 부위 \'등\'이 등산 첫 글자에 들어가서.',
  },
  {
    id: 'pun-b-belly-fruit',
    category: '말장난',
    question: '배(신체)가 제일 좋아하는 과일은?',
    choices: ['사과', '배', '감', '귤'],
    correctIndex: 1,
    note: '신체 배와 과일 배가 같은 말.',
  },
  {
    id: 'pun-b-miner-animal',
    category: '말장난',
    question: '광부가 제일 친근하게 느끼는 동물은?',
    choices: ['두더지', '박쥐', '지렁이', '개미'],
    correctIndex: 0,
    note: '땅속을 파는 광부와 땅을 파는 두더지가 통해서.',
  },
  {
    id: 'pun-b-postman-fruit',
    category: '말장난',
    question: '집배원이 제일 좋아하는 과일은?',
    choices: ['사과', '배', '귤', '감'],
    correctIndex: 1,
    note: '택\'배\'의 배와 과일 배가 같은 말.',
  },
  {
    id: 'pun-b-tooth-city',
    category: '말장난',
    question: '이가 제일 가고 싶어 하는 도시는?',
    choices: ['치앙마이', '나폴리', '마닐라', '로마'],
    correctIndex: 0,
    note: '치아를 뜻하는 \'치\'가 치앙마이 첫 글자에 들어가서.',
  },
  {
    id: 'pun-b-neck-animal',
    category: '말장난',
    question: '목이 제일 부러워하는 동물은?',
    choices: ['기린', '거북이', '두루미', '사슴'],
    correctIndex: 0,
    note: '목이 가장 긴 동물이 기린이라서.',
  },
  {
    id: 'pun-b-sailor-snack',
    category: '말장난',
    question: '선원이 제일 좋아하는 과자는?',
    choices: ['양파링', '오징어땅콩', '감자깡', '꼬깔콘'],
    correctIndex: 1,
    note: '바다에서 나는 오징어로 만든 과자라서.',
  },
  {
    id: 'pun-b-baker-place',
    category: '말장난',
    question: '제빵사가 제일 가기 싫은 동네는?',
    choices: ['반죽동', '발효동', '식빵동', '쉰빵동'],
    correctIndex: 3,
    note: '빵이 상하는 \'쉬다\'를 동네 이름처럼 비튼 말.',
  },
  {
    id: 'pun-b-finger-snack',
    category: '말장난',
    question: '손가락이 제일 좋아하는 과자는?',
    choices: ['빼빼로', '새우깡', '꼬깔콘', '홈런볼'],
    correctIndex: 2,
    note: '손가락 끝에 끼워 먹는 꼬깔콘이라서.',
  },
  {
    id: 'pun-c-coldest-sea',
    category: '말장난',
    question: '세상에서 가장 빠른 새는?',
    choices: ['눈깜짝할새', '제비', '총알새', '번개새'],
    correctIndex: 0,
    note: '\'눈 깜짝할 새\'에 \'새\'를 빗댄 말장난.',
  },
  {
    id: 'pun-c-boring-school',
    category: '말장난',
    question: '세상에서 가장 지루한 중학교는?',
    choices: ['로딩중', '대기중', '고민중', '수업중'],
    correctIndex: 0,
    note: '\'로딩 중\'의 \'중\'을 중학교로 빗댄 말.',
  },
  {
    id: 'pun-c-transparent-house',
    category: '말장난',
    question: '세상에서 가장 투명한 집은?',
    choices: ['유리성', '비닐하우스', '온실집', '수정궁'],
    correctIndex: 1,
    note: '비닐로 지어 속이 비치는 비닐하우스.',
  },
  {
    id: 'pun-c-edible-swallow',
    category: '말장난',
    question: '사람이 먹을 수 있는 제비는?',
    choices: ['강남제비', '흥부제비', '수제비', '손제비'],
    correctIndex: 2,
    note: '손으로 떠 만든 \'수제비\'.',
  },
  {
    id: 'pun-c-king-fall',
    category: '말장난',
    question: '개 중에서 가장 아름다운 개는?',
    choices: ['진돗개', '무지개', '삽살개', '풍산개'],
    correctIndex: 1,
    note: '하늘의 \'무지개\'를 개에 빗댄 말장난.',
  },
  {
    id: 'pun-c-meat-dog',
    category: '말장난',
    question: '고기 먹을 때마다 따라다니는 개는?',
    choices: ['이쑤시개', '집게', '무지개', '번개'],
    correctIndex: 0,
    note: '이를 쑤시는 \'이쑤시개\'의 \'개\'.',
  },
  {
    id: 'pun-c-dirty-clean',
    category: '말장난',
    question: '닦을수록 더 더러워지는 것은?',
    choices: ['거울', '유리창', '걸레', '수건'],
    correctIndex: 2,
    note: '때를 닦아내며 자기는 더러워지는 걸레.',
  },
  {
    id: 'pun-c-newspaper-door',
    category: '말장난',
    question: '아침마다 온 세상을 볼 수 있는 문은?',
    choices: ['대문', '신문', '창문', '정문'],
    correctIndex: 1,
    note: '세상 소식을 다 보는 \'신문(門)\'.',
  },
  {
    id: 'pun-c-candle-cry',
    category: '말장난',
    question: '어두울 때 머리 풀고 눈물 흘리는 것은?',
    choices: ['양초', '전구', '손전등', '가로등'],
    correctIndex: 0,
    note: '심지를 풀고 촛농을 흘리는 양초.',
  },
  {
    id: 'pun-c-vacation-town',
    category: '말장난',
    question: '초등학생이 가장 좋아하는 동네는?',
    choices: ['방학동', '공부동', '시험동', '숙제동'],
    correctIndex: 0,
    note: '방학이 떠오르는 동네 이름 \'방학동\'.',
  },
  {
    id: 'pun-c-usedcar-student',
    category: '말장난',
    question: '중·고등학생이 타는 차는?',
    choices: ['새차', '외제차', '중고차', '경차'],
    correctIndex: 2,
    note: '중학생·고등학생을 줄여 \'중고차\'.',
  },
  {
    id: 'pun-c-dad-car',
    category: '말장난',
    question: '아빠한테 선물하기 좋은 차 이름은?',
    choices: ['소나타', '아반떼', '그랜저', '모닝'],
    correctIndex: 1,
    note: '\'아빠한테~\'와 발음이 비슷한 아반떼.',
  },
  {
    id: 'pun-c-crane-intro',
    category: '말장난',
    question: '학이 자기소개를 하면?',
    choices: ['입학', '방학', '전학', '휴학'],
    correctIndex: 2,
    note: '\'전(저는) 학입니다\' → 전학.',
  },
  {
    id: 'pun-c-hate-pyeon',
    category: '말장난',
    question: '편을 하기 싫은 것을 세 글자로?',
    choices: ['편식함', '편안함', '편가름', '편두통'],
    correctIndex: 1,
    note: '\'편 안 함\' → 편안함.',
  },
  {
    id: 'pun-c-cant-buy-apt',
    category: '말장난',
    question: '어른들은 못 사는 아파트는?',
    choices: ['아이파크', '래미안', '자이', '힐스테이트'],
    correctIndex: 0,
    note: '\'아이(만) 파크\' → 어른은 못 산다.',
  },
  {
    id: 'pun-c-cap-shoe',
    category: '말장난',
    question: '모자 사이에 신발을 두면?',
    choices: ['캡사이신', '모신발', '사이모자', '신모사'],
    correctIndex: 0,
    note: '캡(모자)+사이+신(신발) → 캡사이신.',
  },
  {
    id: 'pun-c-spy-bird',
    category: '말장난',
    question: '간첩이 동물원에서 찾는 새는?',
    choices: ['공작새', '독수리', '앵무새', '참새'],
    correctIndex: 0,
    note: '비밀 \'공작\'을 펴는 공작새.',
  },
  {
    id: 'pun-c-inedible-gam',
    category: '말장난',
    question: '감인데 먹을 수 없는 감은?',
    choices: ['홍시', '곶감', '영감', '단감'],
    correctIndex: 2,
    note: '나이 든 어르신 \'영감\'.',
  },
  {
    id: 'pun-c-mosaic-taekkyeon',
    category: '말장난',
    question: '엄마와 아들이 함께 택견을 하면?',
    choices: ['부자유친', '모자이크', '가족애', '합동기'],
    correctIndex: 1,
    note: '모자(母子)가 \'이크!\' 하면 모자이크.',
  },
  {
    id: 'pun-c-naked-town',
    category: '말장난',
    question: '벌거벗고도 안 부끄러운 곳은?',
    choices: ['목욕탕', '나체촌', '찜질방', '수영장'],
    correctIndex: 0,
    note: '모두 벗고 있는 목욕탕에선 안 부끄럽다.',
  },
  {
    id: 'pun-c-grape-laugh',
    category: '말장난',
    question: '세상에서 가장 빠른 떡은?',
    choices: ['찰떡', '헐레벌떡', '꿀떡', '인절미'],
    correctIndex: 1,
    note: '급히 서두르는 \'헐레벌떡\'에 떡을 빗댄 말장난.',
  },
  {
    id: 'pun-c-cow-laugh-no',
    category: '말장난',
    question: '세상에서 제일 게으른 소는?',
    choices: ['젖소', '누워소', '드러누소', '한우'],
    correctIndex: 2,
    note: '\'드러누우소(눕소)\' → 게으른 소.',
  },
  {
    id: 'pun-c-doctor-fruit',
    category: '말장난',
    question: '의사가 가장 싫어하는 과일은?',
    choices: ['수박', '사과', '바나나', '포도'],
    correctIndex: 1,
    note: '\'사과 하나면 의사가 필요 없다\'는 말에서 온 말장난.',
  },
  {
    id: 'pun-c-light-fish',
    category: '말장난',
    question: '세상에서 가장 가벼운 생선은?',
    choices: ['갈치', '고등어', '날치', '참치'],
    correctIndex: 2,
    note: '하늘을 나는 듯 가벼운 \'날치\'.',
  },
  {
    id: 'pun-c-rich-tree',
    category: '말장난',
    question: '세상에서 가장 부자인 나무는?',
    choices: ['백만장자나무', '돈나무', '감나무', '은행나무'],
    correctIndex: 3,
    note: '돈을 다루는 \'은행\'이 있는 은행나무.',
  },
  {
    id: 'pun-c-cry-vegetable',
    category: '말장난',
    question: '파가 부르르 떨며 화내면?',
    choices: ['양파탱', '파르르', '상추쌈', '열무침'],
    correctIndex: 1,
    note: '파가 \'파르르\' 떠는 말장난.',
  },
  {
    id: 'pun-c-mountain-cry',
    category: '말장난',
    question: '산이 살았다며 웃으면?',
    choices: ['산소', '산뜻', '뫼하하', '산타'],
    correctIndex: 0,
    note: '산이 \'산소(살았소)\' 하며 웃는다는 말.',
  },
  {
    id: 'pun-c-money-soup',
    category: '말장난',
    question: '사람들이 가장 싫어하는 거리는?',
    choices: ['찻길', '걱정거리', '지름길', '골목길'],
    correctIndex: 1,
    note: '고민거리 \'걱정거리\'를 길(거리)처럼 비튼 말장난.',
  },
  {
    id: 'pun-c-fast-train-snack',
    category: '말장난',
    question: '기차가 가장 좋아하는 과자는?',
    choices: ['칙촉', '빼빼로', '쿠크다스', '에이스'],
    correctIndex: 0,
    note: '기차 소리 \'칙칙\'을 닮은 칙촉.',
  },
  {
    id: 'pun-c-sleepy-bug',
    category: '말장난',
    question: '가장 잠이 많은 곤충은?',
    choices: ['나비', '잠자리', '무당벌레', '사슴벌레'],
    correctIndex: 1,
    note: '이름에 \'잠자리\'가 들어간 잠자리.',
  },
  {
    id: 'pun-c-dragon-snack',
    category: '말장난',
    question: '하늘 날던 용이 텅 비면?',
    choices: ['용궁', '병룡', '용가리', '공룡'],
    correctIndex: 3,
    note: '공(空) 친 용, 비어버린 \'공룡\'의 말장난.',
  },
  {
    id: 'pun-c-honest-tree',
    category: '말장난',
    question: '가장 정직한 나무는?',
    choices: ['참나무', '거짓나무', '대나무', '소나무'],
    correctIndex: 0,
    note: '\'참(진실)\'이 들어간 참나무.',
  },
  {
    id: 'pun-c-baby-shoe',
    category: '말장난',
    question: '아기가 가장 좋아하는 신발은?',
    choices: ['운동화', '아장화', '구두', '슬리퍼'],
    correctIndex: 1,
    note: '\'아장아장\' 걷는 아기의 아장화.',
  },
  {
    id: 'pun-c-strong-bean',
    category: '말장난',
    question: '세상에서 가장 힘센 콩은?',
    choices: ['검은콩', '강낭콩', '완두콩', '울끈콩'],
    correctIndex: 1,
    note: '\'강한 콩\' 느낌의 강낭콩 말장난.',
  },
  {
    id: 'pun-c-flying-cat',
    category: '말장난',
    question: '하늘을 나는 고양이는?',
    choices: ['야옹비행', '나비', '날냥이', '공중묘'],
    correctIndex: 1,
    note: '\'나(는) 비(행)\' → 나비의 말장난.',
  },
  {
    id: 'pun-c-angry-rice',
    category: '말장난',
    question: '밥이 화가 나면?',
    choices: ['볶음밥', '비빔밥', '주먹밥', '누룽지'],
    correctIndex: 2,
    note: '\'주먹\' 불끈 쥔 주먹밥.',
  },
  {
    id: 'pun-c-sad-vegetable',
    category: '말장난',
    question: '가장 슬프게 우는 채소는?',
    choices: ['울외', '눈물나물', '우엉', '슬픈배추'],
    correctIndex: 2,
    note: '\'우엉우엉\' 우는 소리 같은 우엉.',
  },
  {
    id: 'pun-c-king-fish',
    category: '말장난',
    question: '바다에서 가장 등급 높은 생선은?',
    choices: ['고등어', '대왕문어', '임금생선', '왕고래'],
    correctIndex: 0,
    note: '높은 \'고등(高等)\'의 고등어 말장난.',
  },
  {
    id: 'pun-c-deepest-well',
    category: '말장난',
    question: '결정 못 하고 망설이는 우물은?',
    choices: ['옹달샘', '고민샘', '우물쭈물', '두레샘'],
    correctIndex: 2,
    note: '결정 못 하고 \'우물쭈물\'하는 우물.',
  },
  {
    id: 'pun-c-runaway-bread',
    category: '말장난',
    question: '도망 잘 치는 빵은?',
    choices: ['바게트', '도넛', '줄행랑빵', '번개빵'],
    correctIndex: 1,
    note: '\'(달아)도 넛(놨)다\' 느낌의 도넛 말장난.',
  },
  {
    id: 'wit-a-train-driver-age',
    category: '재치',
    question: '기차가 100km로 달린다. 운전사 나이는?',
    choices: ['100살', '40살', '당신 나이', '알 수 없음'],
    correctIndex: 2,
    note: '기차를 모는 \'운전사\'가 이 문제를 읽는 당신이라는 함정',
  },
  {
    id: 'wit-a-train-driver-age2',
    category: '재치',
    question: '버스 운전하는 당신, 승객 5명 탔다. 운전사 눈색은?',
    choices: ['검정', '갈색', '당신 눈색', '파랑'],
    correctIndex: 2,
    note: '운전사는 \'당신\' 자신이라 당신 눈동자 색.',
  },
  {
    id: 'wit-a-how-many-months-31',
    category: '재치',
    question: '하루가 25시간인 날은 일 년에 며칠?',
    choices: ['0일', '1일', '2일', '365일'],
    correctIndex: 0,
    note: '하루는 항상 24시간, 25시간인 날은 없다.',
  },
  {
    id: 'wit-a-egg-drop',
    category: '재치',
    question: '날달걀을 2m 아래로 던져도 안 깨지게 하려면?',
    choices: ['천을 깐다', '3m서 던진다', '베개 위로', '쿠션 깐다'],
    correctIndex: 1,
    note: '3m에서 던지면 처음 2m 구간은 안 닿으니 안 깨짐',
  },
  {
    id: 'wit-a-doctor-brother',
    category: '재치',
    question: '의사가 형제 없다는데 의사 형이 \'쟨 내 동생\'이라면?',
    choices: ['거짓말', '여동생', '입양아', '쌍둥이'],
    correctIndex: 1,
    note: '의사는 여자라 \'형제\' 아닌 여동생, 성별 고정관념 함정',
  },
  {
    id: 'wit-a-burning-candle-wind',
    category: '재치',
    question: '바람이 불면 촛불은 어떻게 되나?',
    choices: ['더 잘 탄다', '꺼진다', '색이 변한다', '길어진다'],
    correctIndex: 1,
    note: '촛불은 바람 불면 꺼짐, \'잘 탄다\'는 전제가 함정',
  },
  {
    id: 'wit-a-month-shortest',
    category: '말장난',
    question: '발음하면 이가 가장 시린 달은?',
    choices: ['1월', '11월', '12월', '2월'],
    correctIndex: 3,
    note: '2월은 \'이~월\'이라 이가 시리다, 말장난',
  },
  {
    id: 'wit-a-elevator-button',
    category: '재치',
    question: '10층 사람이 출근땐 1층, 퇴근땐 7층까지만 탄다. 왜?',
    choices: ['운동하려고', '키가 작아서', '고소공포증', '엘베 고장'],
    correctIndex: 1,
    note: '키가 작아 10층 버튼에 손이 안 닿고 7층까지만 누름',
  },
  {
    id: 'wit-a-coin-flip',
    category: '재치',
    question: '동전이 앞면 9번 연속. 10번째 앞면 확률은?',
    choices: ['아주 낮다', '1024분의1', '2분의1', '거의 0'],
    correctIndex: 2,
    note: '매 던지기는 독립이라 언제나 1/2, 도박사의 오류 함정',
  },
  {
    id: 'wit-a-word-spacing',
    category: '재치',
    question: '\'아버지가방에들어가신다\'에서 아버지는 어디로?',
    choices: ['가방 속', '방 안', '부엌', '마당'],
    correctIndex: 1,
    note: '\'아버지가 방에 들어가신다\'로 띄면 방, 띄어쓰기 함정',
  },
  {
    id: 'wit-a-mountain-climb',
    category: '재치',
    question: '산을 오르내릴 때 무릎에 더 부담인 쪽은?',
    choices: ['올라갈 때', '내려올 때', '같다', '둘 다 없음'],
    correctIndex: 1,
    note: '내려올 때 무릎에 체중이 더 실려 관절 부담이 큼',
  },
  {
    id: 'wit-a-glasses-count',
    category: '재치',
    question: '안경 낀 5명 중 진짜 눈 나쁜 사람은?',
    choices: ['5명', '아무도', '멋내기 빼고', '알 수 없다'],
    correctIndex: 3,
    note: '패션·도수없는 안경도 있어 안경=시력나쁨 아님, 단정 함정',
  },
  {
    id: 'wit-a-clock-mirror',
    category: '재치',
    question: '거울에 비친 시계가 3시면 실제 시각은?',
    choices: ['3시', '9시', '6시', '12시'],
    correctIndex: 1,
    note: '거울은 좌우 반전, 3시의 거울상은 9시',
  },
  {
    id: 'wit-a-cold-room',
    category: '재치',
    question: '성냥 하나로 추운 방에서 가장 먼저 켤 것은?',
    choices: ['벽난로', '양초', '난로', '성냥불'],
    correctIndex: 3,
    note: '뭘 켜든 성냥 자체에 먼저 불을 붙여야 함, 순서 함정',
  },
  {
    id: 'wit-a-longest-word',
    category: '재치',
    question: '세상에서 가장 긴 단어는?',
    choices: ['기차', '스파게티', '끝말잇기', '지렁이'],
    correctIndex: 0,
    note: '기차는 길이가 긴 것의 대명사, 말장난 함정',
  },
  {
    id: 'wit-a-empty-glass',
    category: '재치',
    question: '채울수록 가벼워지는 컵은?',
    choices: ['물컵', '빈 컵', '풍선컵', '구멍컵'],
    correctIndex: 2,
    note: '가벼운 기체로 채우면 가벼워짐, \'채움=무거움\' 함정',
  },
  {
    id: 'wit-a-twins-birthday',
    category: '재치',
    question: '같은 부모, 같은 날 태어난 둘이 쌍둥이가 아니다. 왜?',
    choices: ['입양', '세쌍둥이', '나이차', '사촌'],
    correctIndex: 1,
    note: '셋 이상이면 쌍둥이 아닌 세쌍둥이 중 둘, 함정',
  },
  {
    id: 'wit-a-river-cross',
    category: '재치',
    question: '다리·배·헤엄 없이 강을 건너는 방법은?',
    choices: ['뛴다', '얼었을 때', '돌다리', '불가능'],
    correctIndex: 1,
    note: '강이 얼면 걸어서 건넘, \'항상 물\'이라는 전제 함정',
  },
  {
    id: 'wit-a-three-apples',
    category: '재치',
    question: '사과 5개 중 3개를 가져가면 내게 남는 건?',
    choices: ['2개', '3개', '5개', '0개'],
    correctIndex: 1,
    note: '\'가져간\' 3개가 곧 내가 가진 것, 관점 함정',
  },
  {
    id: 'wit-a-noisy-quiet',
    category: '재치',
    question: '소리치면 칠수록 조용해지는 곳은?',
    choices: ['도서관', '경기장', '공연장', '교실'],
    correctIndex: 0,
    note: '도서관에선 떠들면 제지당해 결국 조용해짐',
  },
  {
    id: 'wit-a-day-after',
    category: '재치',
    question: '오늘이 모레의 그저께면 오늘은?',
    choices: ['내일', '어제', '오늘', '모레'],
    correctIndex: 2,
    note: '모레의 그저께(2일 전)는 바로 오늘',
  },
  {
    id: 'wit-a-heavier-question',
    category: '재치',
    question: '먹을수록 입맛만 도는 것은?',
    choices: ['밥', '과자', '약속', '눈치'],
    correctIndex: 1,
    note: '과자는 먹을수록 더 당김, \'먹음=포만\' 함정',
  },
  {
    id: 'wit-a-king-without-crown',
    category: '재치',
    question: '머리가 있는데 모자를 못 쓰는 것은?',
    choices: ['대머리', '압정', '사람', '왕'],
    correctIndex: 1,
    note: '압정·못은 \'머리\'가 있지만 모자를 못 씀, 신체 머리로 오인',
  },
  {
    id: 'wit-a-two-doors',
    category: '재치',
    question: '뜨면 열리고 감으면 닫히는 것은?',
    choices: ['창문', '책', '눈', '입'],
    correctIndex: 2,
    note: '눈을 뜨면 시야가 열리고 감으면 닫힘',
  },
  {
    id: 'wit-a-color-of-bear',
    category: '재치',
    question: '어느 쪽 1km 가도 남쪽뿐인 집의 곰 색은?',
    choices: ['갈색', '검정', '흰색', '회색'],
    correctIndex: 2,
    note: '그 조건은 북극, 북극곰은 흰색, 방향 트릭',
  },
  {
    id: 'wit-a-empty-pocket',
    category: '재치',
    question: '넣을수록 주머니가 가벼워지는 것은?',
    choices: ['돌', '구멍', '솜', '공기'],
    correctIndex: 1,
    note: '구멍을 넣을수록 천이 사라져 가벼워짐, 역설 함정',
  },
  {
    id: 'wit-a-shadow-run',
    category: '재치',
    question: '아무리 빨리 달려도 못 잡는 것은?',
    choices: ['바람', '내 그림자', '앞사람', '시간'],
    correctIndex: 1,
    note: '내 그림자는 늘 같은 거리로 따라와 영원히 못 잡음',
  },
  {
    id: 'wit-a-cup-fall',
    category: '재치',
    question: '카펫 위로 떨어져도 안 깨지는 유리컵은?',
    choices: ['두꺼운 컵', '플라스틱 컵', '안 떨어뜨림', '작은 컵'],
    correctIndex: 2,
    note: '떨어뜨리지 않으면 어떤 컵도 안 깨짐, 전제 함정',
  },
  {
    id: 'wit-a-month-no-r',
    category: '재치',
    question: '한글로 적으면 받침이 없는 달은?',
    choices: ['1월', '3월', '4월', '9월'],
    correctIndex: 2,
    note: '\'사월(4월)\'은 받침이 없음, 한글 발음 기준 함정',
  },
  {
    id: 'wit-a-dry-rain',
    category: '재치',
    question: '비를 맞아도 더 젖지 않는 것은?',
    choices: ['우산', '바다', '비옷', '처마'],
    correctIndex: 1,
    note: '바다는 이미 물이라 더 젖을 게 없음, 관점 함정',
  },
  {
    id: 'wit-a-light-heavy',
    category: '재치',
    question: '낮엔 가볍고 밤엔 무거워지는 것은?',
    choices: ['가방', '눈꺼풀', '돌', '책'],
    correctIndex: 1,
    note: '밤엔 졸려 눈꺼풀이 천근만근, 비유 함정',
  },
  {
    id: 'wit-a-count-family',
    category: '재치',
    question: '형제 7명, 각자 여동생 1명씩. 형제자매는 모두 몇?',
    choices: ['14명', '8명', '16명', '9명'],
    correctIndex: 1,
    note: '여동생은 모두가 공유하는 한 명, 형제7+여동생1=8명',
  },
  {
    id: 'wit-a-fire-water',
    category: '재치',
    question: '물을 부으면 더 커지는 불은?',
    choices: ['장작불', '기름불', '촛불', '모닥불'],
    correctIndex: 1,
    note: '기름 불은 물 부으면 확 번짐, \'물=소화\' 함정',
  },
  {
    id: 'wit-a-no-weight-gold',
    category: '재치',
    question: '많이 가질수록 손해인 금은?',
    choices: ['순금', '벌금', '황금', '금괴'],
    correctIndex: 1,
    note: '벌금은 많을수록 손해, \'금=귀함\' 동음이의 트릭',
  },
  {
    id: 'wit-a-faster-down',
    category: '재치',
    question: '위로 던지면 떨어지고 아래론 못 던지는 것은?',
    choices: ['공', '돌', '그림자', '연기'],
    correctIndex: 3,
    note: '연기는 위로만 올라가 아래로 던질 수 없음',
  },
  {
    id: 'wit-a-two-coins-110',
    category: '재치',
    question: '동전 둘 합 600원, 하나는 500원이 아니다. 무슨 동전?',
    choices: ['불가능', '100·100', '500·100', '50·550'],
    correctIndex: 2,
    note: '한 개\'만\' 500원 아니란 말, 나머지는 500원이라 500+100',
  },
  {
    id: 'wit-a-deep-shallow',
    category: '재치',
    question: '깊을수록 겉으로 적게 드러나는 것은?',
    choices: ['바다', '우물', '생각', '구덩이'],
    correctIndex: 2,
    note: '생각이 깊은 사람은 말을 아껴 적게 드러냄, 비유 함정',
  },
  {
    id: 'wit-a-clean-dirty',
    category: '재치',
    question: '불은 불인데 뜨겁지 않은 불은?',
    choices: ['모닥불', '반딧불', '장작불', '화롯불'],
    correctIndex: 1,
    note: '스스로 빛을 내지만 뜨겁지 않은 반딧불.',
  },
  {
    id: 'wit-a-open-close-umbrella',
    category: '재치',
    question: '비 올 때 펴지만 비를 막진 않는 것은?',
    choices: ['우산', '양산', '천막', '차양'],
    correctIndex: 1,
    note: '양산은 햇빛용이라 비 막는 용도 아님, \'편다=우산\' 함정',
  },
  {
    id: 'wit-a-grow-shrink',
    category: '재치',
    question: '쓸 때만 작아지고 안 쓰면 그대로인 것은?',
    choices: ['연필', '비누', '지우개', '나이'],
    correctIndex: 2,
    note: '지우개는 쓸 때만 닳음, \'안 쓰면 그대로\'가 핵심',
  },
  {
    id: 'wit-a-many-legs',
    category: '재치',
    question: '다리가 넷인데 못 걷는 것은?',
    choices: ['강아지', '책상', '말', '거북이'],
    correctIndex: 1,
    note: '책상은 다리 넷이지만 못 걸음, \'다리=동물\' 함정',
  },
  {
    id: 'logic-a-bar-water',
    category: '상황추론',
    question: '물 달라던 손님이 놀라자 고맙다며 갔다. 왜?',
    choices: ['딸꾹질이라', '물맛 없어서', '돈이 없어서', '장난쳐서'],
    correctIndex: 0,
    note: '딸꾹질엔 놀라게 하는 게 물보다 효과적.',
  },
  {
    id: 'logic-a-barrel-half',
    category: '상황추론',
    question: '통을 안 열고 술이 반 넘게 찼는지 알려면?',
    choices: ['기울여 본다', '무게 재기', '흔들어 보기', '겉 만지기'],
    correctIndex: 0,
    note: '기울여 바닥 보이면 반 이하, 안 보이면 반 이상.',
  },
  {
    id: 'logic-a-burning-rope',
    category: '상황추론',
    question: '고르게 안 타는 끈 두 개로 45분을 재려면?',
    choices: ['양끝+한끝', '반으로 접기', '자로 재기', '천천히 켜기'],
    correctIndex: 0,
    note: '양끝 끈=30분, 그때 둘째 반대끝 점화=15분 추가.',
  },
  {
    id: 'logic-a-how-many-times-subtract',
    category: '상황추론',
    question: '30에서 6을 몇 번 뺄 수 있나?',
    choices: ['한 번', '다섯 번', '여섯 번', '무한히'],
    correctIndex: 0,
    note: '한 번 빼면 30이 아님, 매번 30에서 빼는 건 1회.',
  },
  {
    id: 'logic-a-noah-animals',
    category: '상황추론',
    question: '모세는 방주에 동물을 몇 쌍 태웠나?',
    choices: ['모세 아님', '두 쌍', '한 쌍씩', '일곱 쌍'],
    correctIndex: 0,
    note: '방주는 노아, 전제 자체가 틀린 함정.',
  },
  {
    id: 'logic-a-survivors-bury',
    category: '상황추론',
    question: '비행기가 국경에 추락. 생존자는 어디 묻나?',
    choices: ['안 묻는다', '출발국에', '도착국에', '국경에'],
    correctIndex: 0,
    note: '\'생존자\'는 살아 있는 사람, 묻을 대상이 아님.',
  },
  {
    id: 'logic-a-rooster-egg',
    category: '상황추론',
    question: '지붕 꼭대기 수탉이 낳은 알은 어디로 굴러?',
    choices: ['알 못 낳음', '동쪽', '서쪽', '지붕 따라'],
    correctIndex: 0,
    note: '수탉은 알을 못 낳음, 굴러떨어질 알이 없음.',
  },
  {
    id: 'logic-a-light-switch',
    category: '상황추론',
    question: '밖 스위치 3개 중 방 전구를 한 번에 찾으려면?',
    choices: ['켰다 끄고 켜기', '셋 다 켜기', '순서대로', '전구 흔들기'],
    correctIndex: 0,
    note: '켜짐=정답, 꺼졌지만 따뜻=오래 켠 것, 차가움=나머지.',
  },
  {
    id: 'logic-a-water-jugs',
    category: '상황추론',
    question: '5L·3L 통으로 4L를 담으려면 첫 단계는?',
    choices: ['5L 채우기', '3L 채우기', '둘 다 비우기', '5L 반만'],
    correctIndex: 0,
    note: '5L 채워 3L로 옮기면 2L 남음→비우고 옮겨 다시 채움=4L.',
  },
  {
    id: 'logic-a-fox-goose-bean',
    category: '상황추론',
    question: '여우·거위·콩을 하나씩 옮길 때 맨 먼저는?',
    choices: ['거위', '여우', '콩', '아무거나'],
    correctIndex: 0,
    note: '거위가 가운데 위험요소, 먼저 떼어놓아야 함.',
  },
  {
    id: 'logic-a-day-before-yesterday',
    category: '상황추론',
    question: '그제의 이틀 뒤가 오늘이면, 내일의 이틀 전은?',
    choices: ['어제', '오늘', '그제', '모레'],
    correctIndex: 0,
    note: '정상 달력이므로 내일-2일=어제.',
  },
  {
    id: 'logic-a-photo-man',
    category: '상황추론',
    question: '\'내 아버지의 아들이 이 남자 아버지\'면? (나는 외동)',
    choices: ['나의 아들', '나 자신', '내 아버지', '내 형'],
    correctIndex: 0,
    note: '외동이면 \'내 아버지의 아들\'=나→사진은 내 아들.',
  },
  {
    id: 'logic-a-staircase-count',
    category: '상황추론',
    question: '한 층에 계단 20개. 1층서 5층까지 계단은?',
    choices: ['80개', '100개', '20개', '120개'],
    correctIndex: 0,
    note: '1→5층은 4개 층 차이, 20×4=80.',
  },
  {
    id: 'logic-a-clock-strike',
    category: '상황추론',
    question: '종이 6번 치는 데 5초. 12번 치는 데는?',
    choices: ['11초', '10초', '12초', '6초'],
    correctIndex: 0,
    note: '6번=간격 5개=5초, 1간격 1초→12번=간격 11개=11초.',
  },
  {
    id: 'logic-a-socks-dark',
    category: '상황추론',
    question: '깜깜한데 검정·흰 양말서 같은 색 한 켤레, 최소?',
    choices: ['3짝', '2짝', '4짝', '10짝'],
    correctIndex: 0,
    note: '색 두 종류→3짝이면 반드시 같은 색 2짝(비둘기집).',
  },
  {
    id: 'logic-a-bus-direction',
    category: '상황추론',
    question: '문이 한쪽만 그려진 버스, 어느 쪽으로 가나?',
    choices: ['문 반대쪽', '왼쪽', '오른쪽', '멈춤'],
    correctIndex: 0,
    note: '승하차 문이 안 보이면 그 반대편으로 진행 중.',
  },
  {
    id: 'logic-a-cake-three-cuts',
    category: '상황추론',
    question: '원형 케이크를 3번 잘라 8조각 내려면?',
    choices: ['십자+수평', '8등분', '엇갈려 자르기', '불가능'],
    correctIndex: 0,
    note: '위에서 십자 2번(4조각) 후 옆 수평 1번=8조각.',
  },
  {
    id: 'logic-a-empty-glass',
    category: '재치',
    question: '물 절반. \'반 비었다\'와 \'반 찼다\' 중 맞는 건?',
    choices: ['둘 다 맞다', '반 비었다', '반 찼다', '둘 다 틀림'],
    correctIndex: 0,
    note: '같은 상태의 다른 표현, 사실은 동일.',
  },
  {
    id: 'logic-a-matchstick-equation',
    category: '상황추론',
    question: '성냥식 \'VI=IV\'를 안 옮기고 참으로 만들려면?',
    choices: ['돌려 보기', '한 개 옮기기', '부러뜨리기', '그대로 두기'],
    correctIndex: 0,
    note: '180도 돌리면 IV=VI로 보임.',
  },
  {
    id: 'logic-a-prisoner-hat',
    category: '상황추론',
    question: '줄 선 사람 중 맨 뒤가 가장 유리한 이유는?',
    choices: ['앞을 다 봄', '목소리 커서', '줄 빠져나감', '모자 벗어서'],
    correctIndex: 0,
    note: '맨 뒤는 앞 전부를 봐 정보가 가장 많음.',
  },
  {
    id: 'logic-a-twins-birthday',
    category: '상황추론',
    question: '쌍둥이인데 언니 생일이 동생보다 늦다. 어떻게?',
    choices: ['날짜변경선', '불가능', '조산이라', '입양이라'],
    correctIndex: 0,
    note: '먼저 난 언니가 선 넘은 뒤 동생이 나면 날짜 역전.',
  },
  {
    id: 'logic-a-broken-watch',
    category: '상황추론',
    question: '멈춘 시계와 1분 느린 시계 중 더 자주 맞는 건?',
    choices: ['멈춘 시계', '느린 시계', '둘 다 같다', '항상 느린 것'],
    correctIndex: 0,
    note: '멈춘 시계는 하루 2번 정확, 느린 건 720일에 1번.',
  },
  {
    id: 'logic-a-camel-race',
    category: '상황추론',
    question: '낙타 느리게 가기 시합을 한마디로 끝낸 말은?',
    choices: ['바꿔 타라', '빨리 가라', '멈춰라', '걸어가라'],
    correctIndex: 0,
    note: '바꿔 타면 남의 낙타를 빨리 몰게 됨, 동기 역전.',
  },
  {
    id: 'logic-a-two-doors',
    category: '상황추론',
    question: '진실·거짓 문지기에게 한 번 물어 안전한 문을 찾으려면?',
    choices: ['딴 문지기면?', '어디가 안전?', '넌 거짓말쟁이?', '문이 둘이야?'],
    correctIndex: 0,
    note: '둘 다 거치면 답이 뒤집힘, 그 반대를 택함.',
  },
  {
    id: 'logic-a-melting-ice',
    category: '상황추론',
    question: '컵에 뜬 얼음이 다 녹으면 물이 넘칠까?',
    choices: ['안 넘침', '넘침', '컵 깨짐', '절반만'],
    correctIndex: 0,
    note: '뜬 얼음은 녹은 물 부피만큼 잠겨 있어 수위 그대로.',
  },
  {
    id: 'logic-a-name-the-dog',
    category: '상황추론',
    question: '\'흰둥아\' 불렀는데 검은 개가 왔다. 이상한가?',
    choices: ['안 이상함', '이상함', '색맹이라', '길 잃어서'],
    correctIndex: 0,
    note: '이름과 색은 무관, \'흰둥이\'는 그냥 이름.',
  },
  {
    id: 'logic-a-grandma-age',
    category: '상황추론',
    question: '어머니보다 나이 많은 딸이 있을 수 있나?',
    choices: ['새어머니면', '절대 없다', '입양이면', '쌍둥이면'],
    correctIndex: 0,
    note: '재혼한 새어머니가 의붓딸보다 어릴 수 있음.',
  },
  {
    id: 'logic-a-falling-cat',
    category: '상황추론',
    question: '높은 데서 떨어진 고양이가 낮은 데보다 멀쩡한 이유?',
    choices: ['자세 잡을 틈', '운이 좋아서', '낮은 데 딱딱', '무게 차이'],
    correctIndex: 0,
    note: '공중에서 몸 펴 속도 줄이고 자세 잡을 시간 확보.',
  },
  {
    id: 'logic-a-train-smoke',
    category: '상황추론',
    question: '동쪽으로 달리는 전기기차의 연기는 어디로?',
    choices: ['연기 없음', '서쪽', '동쪽', '위쪽'],
    correctIndex: 0,
    note: '전기기차는 연기를 안 냄.',
  },
  {
    id: 'logic-a-ladder-tide',
    category: '상황추론',
    question: '배 사다리 10칸 중 3칸 잠김. 밀물 들면 몇 칸 더?',
    choices: ['더 안 잠김', '3칸', '5칸', '전부'],
    correctIndex: 0,
    note: '배가 물과 함께 떠올라 잠기는 칸 수 그대로.',
  },
  {
    id: 'logic-a-gift-box',
    category: '상황추론',
    question: '못 믿는 둘이 자물쇠 상자를 안전히 주고받으려면?',
    choices: ['번갈아 잠그기', '열쇠 동봉', '상자 부수기', '택배로'],
    correctIndex: 0,
    note: 'A가 잠가 보내고 B가 자기 자물쇠 추가→A가 자기 것 풀고→B가 마저.',
  },
  {
    id: 'mix-a-favorite-town',
    category: '말장난',
    question: '별이 가장 좋아하는 사탕은?',
    choices: ['솜사탕', '별사탕', '막대사탕', '눈깔사탕'],
    correctIndex: 1,
    note: '이름에 \'별\'이 든 별사탕.',
  },
  {
    id: 'mix-a-flower-city',
    category: '재치',
    question: '추울수록 키가 자라는 것은?',
    choices: ['고드름', '나무', '대나무', '얼음'],
    correctIndex: 0,
    note: '처마에서 얼며 점점 길어지는 고드름.',
  },
  {
    id: 'mix-a-black-heart',
    category: '말장난',
    question: '날마다 가슴에 흑심을 품은 것은?',
    choices: ['지우개', '연필', '자', '공책'],
    correctIndex: 1,
    note: '연필 속의 검은 심(흑심) 말장난.',
  },
  {
    id: 'mix-a-number-devil',
    category: '말장난',
    question: '악마의 반대를 숫자로 하면?',
    choices: ['6', '666', '1004', '777'],
    correctIndex: 2,
    note: '1004는 \'천사\'로 읽히는 숫자 말장난.',
  },
  {
    id: 'mix-a-cold-number',
    category: '말장난',
    question: '0을 부르는 다른 말은?',
    choices: ['빵', '구', '팔', '칠'],
    correctIndex: 0,
    note: '0을 \'빵(영)\'이라 읽는 말장난.',
  },
  {
    id: 'mix-a-snowman-job',
    category: '재치',
    question: '눈사람이 가장 무서워하는 계절은?',
    choices: ['봄', '여름', '가을', '겨울'],
    correctIndex: 1,
    note: '한여름 더위에 흔적도 없이 녹아버리니까.',
  },
  {
    id: 'mix-a-spring-flower',
    category: '말장난',
    question: '봄에 가장 먼저 인사하는 꽃은?',
    choices: ['안녕꽃', '개나리', '진달래', '목련'],
    correctIndex: 1,
    note: '\'개나리\'를 \'걔 나리\'처럼 들리게 한 인사 말장난.',
  },
  {
    id: 'mix-a-summer-fruit',
    category: '재치',
    question: '여름에 시원하게 박장대소하는 과일은?',
    choices: ['사과', '수박', '참외', '자두'],
    correctIndex: 1,
    note: '속이 빨개지도록 \'박\'장대소하는 수박.',
  },
  {
    id: 'mix-a-school-bell',
    category: '재치',
    question: '학생이 하루 중 가장 반기는 소리는?',
    choices: ['수업 종', '쉬는 종', '지각 종', '청소 종'],
    correctIndex: 1,
    note: '쉬는 시간을 알리는 종이 제일 반갑다.',
  },
  {
    id: 'mix-a-eraser-fear',
    category: '재치',
    question: '지우개가 가장 무서워하는 말은?',
    choices: ['깨끗이', '틀렸어', '잘했어', '고쳐써'],
    correctIndex: 3,
    note: '고쳐 쓸수록 자기 몸이 닳으니까.',
  },
  {
    id: 'mix-a-number-egg',
    category: '재치',
    question: '닭이 가장 좋아하는 숫자는?',
    choices: ['2', '9', '0', '5'],
    correctIndex: 2,
    note: '0이 달걀(알) 모양이라서.',
  },
  {
    id: 'mix-a-clock-run',
    category: '재치',
    question: '하루 종일 달려도 제자리인 것은?',
    choices: ['바퀴', '시계', '팽이', '쳇바퀴'],
    correctIndex: 1,
    note: '시곗바늘은 돌고 돌아도 같은 자리.',
  },
  {
    id: 'mix-a-cold-soup',
    category: '말장난',
    question: '감기 걸린 사람이 흘리며 먹는 국은?',
    choices: ['미역국', '콧국', '된장국', '북엇국'],
    correctIndex: 1,
    note: '코를 훌쩍이며 먹는 \'콧국\'(콧물) 말장난.',
  },
  {
    id: 'mix-a-fridge-talk',
    category: '재치',
    question: '냉장고가 가장 자주 하는 말은?',
    choices: ['덥다', '시원해', '문 닫아', '배고파'],
    correctIndex: 2,
    note: '문 열어두면 찬 기운이 새니까 \'문 닫아\'.',
  },
  {
    id: 'mix-a-umbrella-shy',
    category: '재치',
    question: '맑은 날 가장 풀 죽는 물건은?',
    choices: ['선풍기', '우산', '모자', '장화'],
    correctIndex: 1,
    note: '비가 안 오면 쓸모없어 접혀 있는 우산.',
  },
  {
    id: 'mix-a-pencil-diet',
    category: '재치',
    question: '쓸수록 살이 빠지는 것은?',
    choices: ['지우개', '연필', '공책', '자'],
    correctIndex: 1,
    note: '쓸수록 짧아져 날씬해지는 연필.',
  },
  {
    id: 'mix-a-window-cry',
    category: '재치',
    question: '추운 날 창문에 맺히는 것은?',
    choices: ['눈물', '성에', '비', '바람'],
    correctIndex: 1,
    note: '실내외 온도차로 맺히는 성에.',
  },
  {
    id: 'mix-a-snow-letter',
    category: '말장난',
    question: '눈(雪)에 발자국을 콱 찍으면?',
    choices: ['설명', '눈치', '눈도장', '눈밭'],
    correctIndex: 2,
    note: '눈에 꾹 찍은 \'눈도장\' 말장난.',
  },
  {
    id: 'mix-a-school-fast',
    category: '재치',
    question: '학교에서 가장 빨리 사라지는 것은?',
    choices: ['분필', '급식', '칠판', '책상'],
    correctIndex: 1,
    note: '순식간에 동나는 급식의 인기.',
  },
  {
    id: 'mix-a-number-bread',
    category: '말장난',
    question: '병은 병인데 깨지지 않는 병은?',
    choices: ['꾀병', '유리병', '물병', '주스병'],
    correctIndex: 0,
    note: '아픈 척하는 \'꾀병\'은 깨지지 않는 병.',
  },
  {
    id: 'mix-a-hot-summer',
    category: '재치',
    question: '여름에 가장 인기 없는 옷은?',
    choices: ['반팔', '민소매', '패딩', '수영복'],
    correctIndex: 2,
    note: '더운데 두꺼운 패딩은 외면받는다.',
  },
  {
    id: 'mix-a-broom-dance',
    category: '재치',
    question: '청소 시간에 춤을 제일 잘 추는 것은?',
    choices: ['걸레', '빗자루', '쓰레받기', '대걸레'],
    correctIndex: 1,
    note: '이리저리 흔드는 빗자루의 춤사위.',
  },
  {
    id: 'mix-a-leaf-fall',
    category: '재치',
    question: '가을에 나무가 가장 많이 떨구는 것은?',
    choices: ['눈물', '낙엽', '열매', '그림자'],
    correctIndex: 1,
    note: '가을의 상징, 떨어지는 낙엽.',
  },
  {
    id: 'mix-a-mirror-honest',
    category: '재치',
    question: '거짓말을 절대 못 하는 물건은?',
    choices: ['저울', '거울', '시계', '달력'],
    correctIndex: 1,
    note: '있는 그대로만 비추는 정직한 거울.',
  },
  {
    id: 'mix-a-number-couple',
    category: '재치',
    question: '연인들이 가장 좋아하는 숫자는?',
    choices: ['1', '2', '4', '7'],
    correctIndex: 1,
    note: '둘이 함께라는 의미의 2.',
  },
  {
    id: 'mix-a-fan-summer',
    category: '재치',
    question: '여름에 가장 고개를 많이 젓는 것은?',
    choices: ['에어컨', '선풍기', '부채', '냉장고'],
    correctIndex: 1,
    note: '좌우로 고개 돌리며 도는 선풍기.',
  },
  {
    id: 'mix-a-test-cold',
    category: '재치',
    question: '성적표를 받으면 등골이 서늘해지는 이유는?',
    choices: ['에어컨', '낮은 점수', '바람', '겨울'],
    correctIndex: 1,
    note: '점수에 등골이 서늘해진다는 재치.',
  },
  {
    id: 'mix-a-candle-short',
    category: '재치',
    question: '키가 클수록 수명이 짧아지는 것은?',
    choices: ['나무', '양초', '대나무', '해바라기'],
    correctIndex: 1,
    note: '길어도 타들어가면 줄어드는 양초.',
  },
  {
    id: 'mix-a-ruler-straight',
    category: '말장난',
    question: '평생 곧은 마음만 가진 학용품은?',
    choices: ['자', '연필', '풀', '가위'],
    correctIndex: 0,
    note: '항상 직선(곧은)인 \'자\'의 말장난.',
  },
  {
    id: 'mix-a-number-ten',
    category: '재치',
    question: '두 손이 가장 좋아하는 숫자는?',
    choices: ['5', '10', '7', '3'],
    correctIndex: 1,
    note: '두 손 손가락이 모두 10개라서.',
  },
  {
    id: 'mix-a-soap-thin',
    category: '재치',
    question: '씻을수록 야위어 가는 것은?',
    choices: ['수건', '비누', '칫솔', '빗'],
    correctIndex: 1,
    note: '쓸수록 작아지는 비누.',
  },
  {
    id: 'mix-a-winter-white',
    category: '재치',
    question: '겨울에 온 세상을 하얗게 칠하는 것은?',
    choices: ['바람', '눈', '서리', '구름'],
    correctIndex: 1,
    note: '세상을 하얗게 덮는 눈.',
  },
  {
    id: 'mix-a-bag-back',
    category: '재치',
    question: '학생 등에 늘 업혀 다니는 것은?',
    choices: ['체육복', '책가방', '실내화', '도시락'],
    correctIndex: 1,
    note: '등에 메고 다니는 책가방.',
  },
  {
    id: 'mix-a-number-eight',
    category: '재치',
    question: '옆으로 누우면 무한대가 되는 숫자는?',
    choices: ['6', '8', '3', '0'],
    correctIndex: 1,
    note: '8을 눕히면 무한대(∞) 기호가 된다.',
  },
  {
    id: 'mix-a-spring-sneeze',
    category: '재치',
    question: '봄에 코가 가장 바빠지는 이유는?',
    choices: ['감기', '꽃가루', '황사', '더위'],
    correctIndex: 1,
    note: '봄철 꽃가루로 재채기가 늘어난다.',
  },
  {
    id: 'mix-a-clock-tired',
    category: '재치',
    question: '쉬지 않고 일해도 손이 두 개뿐인 것은?',
    choices: ['로봇', '시계', '인형', '허수아비'],
    correctIndex: 1,
    note: '쉬지 않고 도는 시계의 시침·분침.',
  },
  {
    id: 'mix-a-melon-summer',
    category: '말장난',
    question: '여름에 잘 참는 노란 과일은?',
    choices: ['참외', '수박', '멜론', '포도'],
    correctIndex: 0,
    note: '\'참\'을 잘하는 과일, 참외의 말장난.',
  },
  {
    id: 'mix-a-chalk-white',
    category: '재치',
    question: '칠판 앞에서 점점 작아지는 것은?',
    choices: ['지우개', '분필', '칠판', '마커'],
    correctIndex: 1,
    note: '쓸수록 닳아 짧아지는 분필.',
  },
  {
    id: 'mix-a-number-zero-hero',
    category: '재치',
    question: '혼자선 없지만 뒤에 붙으면 세지는 숫자는?',
    choices: ['1', '0', '9', '5'],
    correctIndex: 1,
    note: '0은 혼자 없음이지만 붙으면 자릿수를 키운다.',
  },
  {
    id: 'mix-a-blanket-winter',
    category: '재치',
    question: '겨울에 가장 인기 많은 침구는?',
    choices: ['베개', '이불', '요', '담요'],
    correctIndex: 1,
    note: '포근해서 손이 가는 겨울 이불.',
  },
  {
    id: 'mix-a-shoe-pair',
    category: '재치',
    question: '늘 둘이 다니지만 절대 안 붙는 것은?',
    choices: ['젓가락', '신발', '장갑', '양말'],
    correctIndex: 1,
    note: '좌우 한 켤레지만 떨어져 신는 신발.',
  },
  {
    id: 'mix-a-towel-dry',
    category: '재치',
    question: '젖을수록 제 역할을 다하는 것은?',
    choices: ['우산', '수건', '장화', '비옷'],
    correctIndex: 1,
    note: '물기를 빨아들여 젖어야 일하는 수건.',
  },
  {
    id: 'pun-d-soda-cousin',
    category: '말장난',
    question: '사이다가 화나면 부르는 친척은?',
    choices: ['사촌', '고모', '이모', '삼촌'],
    correctIndex: 0,
    note: '\'사이다\'와 \'사촌\'의 \'사\' 말장난',
  },
  {
    id: 'pun-d-carpenter-laugh',
    category: '말장난',
    question: '목수가 가장 잘 웃는 웃음은?',
    choices: ['톱톱', '하하', '낄낄', '껄껄'],
    correctIndex: 0,
    note: '목수의 연장 \'톱\'을 웃음소리처럼',
  },
  {
    id: 'pun-d-summer-drink',
    category: '말장난',
    question: '세종대왕이 만든 우유는?',
    choices: ['딸기우유', '아야어여 우유', '바나나우유', '초코우유'],
    correctIndex: 1,
    note: '한글 모음 \'아야어여오요우유\'를 활용한 말장난.',
  },
  {
    id: 'pun-d-proverb-pig',
    category: '말장난',
    question: '돼지가 가장 싫어하는 죽은?',
    choices: ['꿀꿀이죽', '식은죽', '미음', '팥죽'],
    correctIndex: 0,
    note: '돼지 울음 \'꿀꿀\'을 넣은 말장난',
  },
  {
    id: 'pun-d-uncle-job',
    category: '말장난',
    question: '엄마가 길을 잃으면?',
    choices: ['길치', '맘마미아', '마마보이', '미아'],
    correctIndex: 1,
    note: '엄마(mamma)와 \'Mamma mia\'를 엮은 말장난.',
  },
  {
    id: 'pun-d-cloud-bread',
    category: '말장난',
    question: '하늘이 굽는 빵은?',
    choices: ['구름빵', '식빵', '단팥빵', '크림빵'],
    correctIndex: 0,
    note: '하늘의 \'구름\'을 빵으로 본 합성어',
  },
  {
    id: 'pun-d-coffee-honest',
    category: '말장난',
    question: '오리를 생으로 먹으면?',
    choices: ['회오리', '오리탕', '훈제오리', '오리구이'],
    correctIndex: 0,
    note: '날것 \'회(膾)\'와 오리를 합친 \'회오리\' 말장난.',
  },
  {
    id: 'pun-d-autumn-stamp',
    category: '말장난',
    question: '가을이 제일 좋아하는 놀이는?',
    choices: ['단풍놀이', '수영', '스키', '축구'],
    correctIndex: 0,
    note: '가을 \'단풍\'을 놀이로',
  },
  {
    id: 'pun-d-driver-music',
    category: '말장난',
    question: '운전사가 가장 좋아하는 음악은?',
    choices: ['빵빵', '랩', '발라드', '트로트'],
    correctIndex: 0,
    note: '경적 \'빵빵\'을 음악처럼',
  },
  {
    id: 'pun-d-grandma-phone',
    category: '말장난',
    question: '손주가 사 드리는 효심 가득한 폰은?',
    choices: ['효도폰', '폴더폰', '터치폰', '스마트폰'],
    correctIndex: 0,
    note: '손주가 드리는 \'효도폰\'',
  },
  {
    id: 'pun-d-snow-flake-letter',
    category: '말장난',
    question: '눈이 겨울에 송이송이 보내는 것은?',
    choices: ['눈송이', '눈물', '우편', '엽서'],
    correctIndex: 0,
    note: '송이송이 \'보내는\' 눈송이',
  },
  {
    id: 'pun-d-fish-school',
    category: '말장난',
    question: '물고기가 다니는 학원은?',
    choices: ['어학원', '미술학원', '피아노', '태권도'],
    correctIndex: 0,
    note: '물고기 어(魚)와 어학원의 동음',
  },
  {
    id: 'pun-d-baker-dance',
    category: '말장난',
    question: '제빵사가 제일 잘 추는 춤은?',
    choices: ['반죽', '왈츠', '탱고', '살사'],
    correctIndex: 0,
    note: '빵 \'반죽\'을 춤 이름처럼',
  },
  {
    id: 'pun-d-thunder-angry',
    category: '말장난',
    question: '천둥이 화나면 내는 소리는?',
    choices: ['우르릉', '깔깔', '흥흥', '쯧쯧'],
    correctIndex: 0,
    note: '천둥 의성어 \'우르릉\'',
  },
  {
    id: 'pun-d-proverb-frog',
    category: '말장난',
    question: '개구리가 좋아하는 말 반복은?',
    choices: ['개굴개굴', '우물안', '천리길', '백지장'],
    correctIndex: 0,
    note: '개구리 울음 \'개굴\'',
  },
  {
    id: 'pun-d-spring-makeup',
    category: '말장난',
    question: '봄이 하는 화장은?',
    choices: ['꽃단장', '쌩얼', '떡칠', '민낯'],
    correctIndex: 0,
    note: '봄에 꽃으로 \'꽃단장\'',
  },
  {
    id: 'pun-d-teacher-fruit',
    category: '말장난',
    question: '선생님이 제일 좋아하는 과일은?',
    choices: ['참외', '사과', '수박', '바나나'],
    correctIndex: 0,
    note: '\'참 잘했어요\' 외친다는 참외',
  },
  {
    id: 'pun-d-cousin-tall',
    category: '말장난',
    question: '키가 제일 큰 친척은?',
    choices: ['큰아빠', '막내', '조카', '사촌'],
    correctIndex: 0,
    note: '호칭 \'큰\'을 키가 크다로',
  },
  {
    id: 'pun-d-fog-shy',
    category: '재치',
    question: '부끄러움이 많은 날씨는?',
    choices: ['안개', '폭염', '장마', '강풍'],
    correctIndex: 0,
    note: '얼굴 가려 \'안 보이게\' 하는 안개',
  },
  {
    id: 'pun-d-fireman-veg',
    category: '재치',
    question: '화가 나면 새빨개지는 채소는?',
    choices: ['고추', '오이', '양배추', '깻잎'],
    correctIndex: 0,
    note: '매워서 빨갛게 익는 고추를 화에 빗댄 재치.',
  },
  {
    id: 'pun-d-rice-cake-king',
    category: '말장난',
    question: '떡 중에서 제일 높은 떡은?',
    choices: ['임금떡', '꿀떡', '찰떡', '송편'],
    correctIndex: 0,
    note: '가장 높은 \'임금님\' 떡',
  },
  {
    id: 'pun-d-proverb-bird',
    category: '말장난',
    question: '새가 가장 좋아하는 사자성어는?',
    choices: ['새옹지마', '천리길', '돌다리', '낮말'],
    correctIndex: 0,
    note: '\'새옹지마\'의 \'새\'를 새(鳥)로',
  },
  {
    id: 'pun-d-aunt-bag',
    category: '말장난',
    question: '이모가 들고 다니는 큰 가방은?',
    choices: ['이민가방', '핸드백', '에코백', '배낭'],
    correctIndex: 0,
    note: '\'이모\'와 \'이민가방\'의 \'이\'',
  },
  {
    id: 'pun-d-cold-greeting',
    category: '말장난',
    question: '감기가 인사할 때 하는 말은?',
    choices: ['콜록콜록', '헬로', '방가', '하이'],
    correctIndex: 0,
    note: '기침 \'콜록\'을 인사말로',
  },
  {
    id: 'pun-d-painter-color',
    category: '말장난',
    question: '밥은 밥인데 못 먹는 밥은?',
    choices: ['톱밥', '주먹밥', '볶음밥', '김밥'],
    correctIndex: 0,
    note: '톱질에서 나오는 \'톱밥\'은 먹을 수 없다.',
  },
  {
    id: 'pun-d-wind-instrument',
    category: '말장난',
    question: '바람이 잘 부는 악기는?',
    choices: ['휘파람', '드럼', '기타', '피아노'],
    correctIndex: 0,
    note: '입으로 부는 \'휘파람\'의 \'파람\'',
  },
  {
    id: 'pun-d-hail-temper',
    category: '재치',
    question: '성격이 제일 급한 날씨는?',
    choices: ['우박', '이슬', '서리', '무지개'],
    correctIndex: 0,
    note: '갑자기 쏟아지는 우박',
  },
  {
    id: 'wit-b-king-pig',
    category: '말장난',
    question: '돼지가 다스리는 나라의 왕은?',
    choices: ['돼왕', '꿀꿀이', '꿀돼지', '꿀꿀왕'],
    correctIndex: 0,
    note: '\'돼지 왕\'을 줄여 돼왕',
  },
  {
    id: 'wit-b-old-spider',
    category: '말장난',
    question: '가장 나이 많은 거미는?',
    choices: ['할미거미', '왕거미', '독거미', '무당거미'],
    correctIndex: 0,
    note: '할머니 \'할미\'+거미',
  },
  {
    id: 'wit-b-crying-fruit',
    category: '말장난',
    question: '항상 우는 채소는?',
    choices: ['울외', '사과', '앵두', '바나나'],
    correctIndex: 0,
    note: '\'울다\'+채소 외',
  },
  {
    id: 'wit-b-hot-dog',
    category: '재치',
    question: '세상에서 가장 더운 개는?',
    choices: ['핫도그', '삽살개', '진돗개', '불개'],
    correctIndex: 0,
    note: 'hot dog를 더운 개로 직역',
  },
  {
    id: 'wit-b-laughing-flower',
    category: '재치',
    question: '분위기 좋을 때 활짝 피는 꽃은?',
    choices: ['웃음꽃', '해바라기', '나리꽃', '장미'],
    correctIndex: 0,
    note: '\'웃음꽃\'을 진짜 꽃처럼',
  },
  {
    id: 'wit-b-king-bread',
    category: '말장난',
    question: '세상에서 가장 슬픈 별은?',
    choices: ['샛별', '이별', '북극성', '별똥별'],
    correctIndex: 1,
    note: '헤어짐 \'이별\'을 별에 빗댄 말장난.',
  },
  {
    id: 'wit-b-shy-vegetable',
    category: '말장난',
    question: '부끄럼 많은 채소는?',
    choices: ['부추', '당근', '시금치', '양파'],
    correctIndex: 0,
    note: '\'부끄\'와 부추',
  },
  {
    id: 'wit-b-busy-bug',
    category: '말장난',
    question: '가장 바쁜 곤충은?',
    choices: ['바삐', '나비', '개미', '잠자리'],
    correctIndex: 0,
    note: '바쁘다 \'바삐\'',
  },
  {
    id: 'wit-b-angry-drink',
    category: '말장난',
    question: '화가 잔뜩 난 음료는?',
    choices: ['화채', '콜라', '사이다', '식혜'],
    correctIndex: 0,
    note: '\'화\'를 화남으로 읽은 화채',
  },
  {
    id: 'wit-b-thin-book',
    category: '말장난',
    question: '세상에서 가장 가난한 왕은?',
    choices: ['폭군', '최저임금', '대왕', '상감마마'],
    correctIndex: 1,
    note: '왕을 뜻하는 \'임금\'을 급여 \'임금\'으로 바꾼 말장난.',
  },
  {
    id: 'wit-b-warm-color',
    category: '재치',
    question: '가장 따뜻한 색 종류는?',
    choices: ['난색', '빨강', '주황', '원색'],
    correctIndex: 0,
    note: '따뜻할 난을 쓴 \'난색\'',
  },
  {
    id: 'wit-b-honest-animal',
    category: '말장난',
    question: '거짓말 안 하는 참된 새는?',
    choices: ['참새', '여우', '까치', '제비'],
    correctIndex: 0,
    note: '진짜 \'참\'을 참새로',
  },
  {
    id: 'wit-b-tall-noodle',
    category: '말장난',
    question: '키가 제일 당당한 국수는?',
    choices: ['당면', '우동', '칼국수', '쫄면'],
    correctIndex: 0,
    note: '\'당당\'과 당면',
  },
  {
    id: 'logic-b-broken-window',
    category: '말장난',
    question: '세상에서 가장 억울한 도형은?',
    choices: ['삼각형', '원', '사각형', '마름모'],
    correctIndex: 1,
    note: '\'원통하다(억울하다)\'의 원을 도형 원에 빗댄 말장난.',
  },
  {
    id: 'logic-b-two-doors',
    category: '말장난',
    question: '손으로 못 여는 문은?',
    choices: ['소문', '방문', '대문', '창문'],
    correctIndex: 0,
    note: '퍼지는 \'소문\'',
  },
  {
    id: 'logic-b-cold-month',
    category: '재치',
    question: '눈 뜨면 사라지는 건?',
    choices: ['어둠', '별', '눈물', '시야'],
    correctIndex: 0,
    note: '눈 감으면 보이는 어둠은 뜨면 사라짐',
  },
  {
    id: 'logic-b-no-weight',
    category: '재치',
    question: '손에 쥐면 사라지는 건?',
    choices: ['연기', '모래', '얼음', '물'],
    correctIndex: 0,
    note: '움켜쥐면 흩어지는 연기',
  },
  {
    id: 'logic-b-runs-no-legs',
    category: '재치',
    question: '다리 없이 달리는 건?',
    choices: ['강물', '자전거', '바람', '시계'],
    correctIndex: 0,
    note: '\'강물이 흐른다\'를 달린다로',
  },
  {
    id: 'logic-b-full-empty',
    category: '재치',
    question: '파낼수록 커지는 건?',
    choices: ['구덩이', '쓰레기', '빚', '나이'],
    correctIndex: 0,
    note: '흙을 버려 파낼수록 구덩이는 커짐',
  },
  {
    id: 'logic-b-silent-loud',
    category: '재치',
    question: '조용할수록 잘 들리는 건?',
    choices: ['심장소리', '음악', '침묵', '바람'],
    correctIndex: 0,
    note: '고요하면 자기 심장소리가 들림',
  },
  {
    id: 'logic-b-wet-while-drying',
    category: '재치',
    question: '말려주며 스스로 젖는 건?',
    choices: ['수건', '빨래', '머리', '햇빛'],
    correctIndex: 0,
    note: '몸 닦는 수건은 젖음',
  },
  {
    id: 'logic-b-house-no-door',
    category: '재치',
    question: '문도 창도 없는 집은?',
    choices: ['달팽이집', '오두막', '새집', '벌집'],
    correctIndex: 0,
    note: '등에 진 달팽이집',
  },
  {
    id: 'logic-b-catch-not-throw',
    category: '말장난',
    question: '차는 차인데 못 타는 차는?',
    choices: ['녹차', '기차', '버스', '자전거'],
    correctIndex: 0,
    note: '마시는 \'녹차\'는 탈 수 없는 차.',
  },
  {
    id: 'pun-e-palindrome-tomato',
    category: '말장난',
    question: '거꾸로 읽어도 똑같은 채소는?',
    choices: ['토마토', '오이', '당근', '배추'],
    correctIndex: 0,
    note: '\'토마토\'는 거꾸로 읽어도 토마토.',
  },
  {
    id: 'pun-e-palindrome-goose',
    category: '말장난',
    question: '거꾸로 읽어도 똑같은 새는?',
    choices: ['참새', '기러기', '제비', '까치'],
    correctIndex: 1,
    note: '\'기러기\'는 거꾸로 읽어도 기러기.',
  },
  {
    id: 'pun-e-palindrome-swiss',
    category: '말장난',
    question: '거꾸로 읽어도 똑같은 나라는?',
    choices: ['스위스', '스페인', '스웨덴', '프랑스'],
    correctIndex: 0,
    note: '\'스위스\'는 거꾸로 읽어도 스위스.',
  },
  {
    id: 'wit-c-toothpaste',
    category: '재치',
    question: '약처럼 생겼지만 먹으면 안 되는 것은?',
    choices: ['감기약', '치약', '소화제', '영양제'],
    correctIndex: 1,
    note: '치약은 이를 닦는 것, 먹는 약이 아니다.',
  },
];

// id 사전순 정렬 — 추출 결정성을 풀의 삽입 순서와 분리한다(trivia와 동일 규약).
export const NONSENSE_POOL_SORTED: readonly NonsenseQuestion[] = [...NONSENSE_POOL].sort((a, b) =>
  a.id < b.id ? -1 : a.id > b.id ? 1 : 0,
);
