// 넌센스 퀴즈 문제 풀. 한국어 전용. 가볍고 누구나 웃는 파티 톤 — 말장난·언어유희와
// 재치(전제 뒤집기·엉뚱한 논리)를 섞는다. 정치·종교·민감 주제 제외. trivia와 동일 스키마라
// trivia 엔진(buildQuizPlan/computeQuizResult)이 그대로 채점·재생한다.
//
// 문항 추가: 배열 끝에 append하고 새 id(kebab-case)만 부여. 기존 순서 바꾸지 말 것 —
// 서버가 seed 기반으로 섞고, 풀 자체는 런타임에 id 사전순(NONSENSE_POOL_SORTED)으로
// 정렬한 뒤 추출하므로 삽입 순서는 결정성에 영향 없음.
//
// 카피 규칙: question ~40자, choices 각 ~10자(모바일 한 줄). 정답 외 3개는 그럴싸한 함정.
//
// 입고 게이트 — 새 문항은 아래 5개를 전부 통과해야 한다(자세한 근거는 CLAUDE.md):
//  1) 정답이 실제 통용되는 말장난·단어일 것. 이 풀을 위해 지어낸 조어 금지.
//  2) 정답 공개 순간 note 없이도 납득될 것. note는 보조 설명이지 정당화 수단이 아님.
//  3) 오답 3개가 정답과 경합하지 않을 것. 여러 보기가 말이 되면 복수 정답 — 탈락.
//  4) 문제당 답변 시간 6초 안에 읽고 웃을 수 있을 것. 다단계 논리퍼즐 금지.
//  5) 기존 문항과 소재·템플릿·정답이 겹치지 않을 것.

export type NonsenseCategory = '말장난' | '재치';

export type NonsenseQuestion = {
  id: string;
  category: NonsenseCategory;
  question: string;
  choices: readonly [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  /** 정답 공개 화면에 뜨는 한 줄 해설. ≤80자. 답이 자명하면 생략. */
  note?: string;
};

export const NONSENSE_POOL: readonly NonsenseQuestion[] = [
  // ── 말장난 ────────────────────────────────────────────────────
  {
    id: 'pun-king-fall',
    category: '말장난',
    question: '왕이 넘어지면?',
    choices: ['임금님', '킹콩', '왕쾅', '폭삭'],
    correctIndex: 1,
    note: "킹(king)이 '콩' 하고 넘어졌으니 킹콩.",
  },
  {
    id: 'pun-fast-chicken',
    category: '말장난',
    question: '세상에서 가장 빠른 닭은?',
    choices: ['번개닭', '후다닭', '제트닭', '총알닭'],
    correctIndex: 1,
    note: "'후다닥' + 닭.",
  },
  {
    id: 'pun-cold-sea',
    category: '말장난',
    question: '세상에서 가장 추운 바다는?',
    choices: ['북극해', '동해', '썰렁해', '냉해'],
    correctIndex: 2,
    note: '썰렁해~',
  },
  {
    id: 'pun-two-foot-cow',
    category: '말장난',
    question: '발이 두 개 달린 소는?',
    choices: ['정육점', '외양간', '이발소', '목장'],
    correctIndex: 2,
    note: '이(2)발 + 소 = 이발소.',
  },
  {
    id: 'pun-kind-lion',
    category: '말장난',
    question: '세상에서 가장 친절한 사자는?',
    choices: ['의사', '자원봉사자', '변호사', '요리사'],
    correctIndex: 1,
    note: "봉사 + '자'로 끝나는 사자(者).",
  },
  {
    id: 'pun-thief-icecream',
    category: '말장난',
    question: '도둑이 가장 무서워하는 아이스크림은?',
    choices: ['월드콘', '스크류바', '누가바', '빵빠레'],
    correctIndex: 2,
    note: "'누가 봐?'",
  },
  {
    id: 'pun-hot-fruit',
    category: '말장난',
    question: '세상에서 가장 뜨거운 과일은?',
    choices: ['한라봉', '천도복숭아', '파인애플', '용과'],
    correctIndex: 1,
    note: '천도(1000도) 복숭아.',
  },
  {
    id: 'pun-high-chief',
    category: '말장난',
    question: '추장보다 높은 사람은?',
    choices: ['부족장', '고추장', '대추장', '면장'],
    correctIndex: 1,
    note: '고(高) + 추장.',
  },
  {
    id: 'pun-dirty-river',
    category: '말장난',
    question: '세상에서 가장 더러운 강은?',
    choices: ['한강', '낙동강', '요강', '압록강'],
    correctIndex: 2,
    note: '요강(옛날 실내 변기).',
  },
  {
    id: 'pun-laughing-cow',
    category: '말장난',
    question: '소가 크게 웃으면?',
    choices: ['음매', '우하하', '깔깔', '메에'],
    correctIndex: 1,
    note: '소 우(牛) + 하하.',
  },
  {
    id: 'pun-burger-color',
    category: '말장난',
    question: '물고기의 반대말은?',
    choices: ['붕어', '불고기', '생선', '잉어'],
    correctIndex: 1,
    note: "물고기의 '물'을 '불'로 바꾼 불고기 말장난.",
  },
  {
    id: 'pun-dad-lost',
    category: '말장난',
    question: '아빠가 길을 잃으면?',
    choices: ['길치', '파파라치', '마마보이', '미아'],
    correctIndex: 1,
    note: '파파(아빠) + 라치.',
  },

  // ── 재치 ─────────────────────────────────────────────────────
  {
    id: 'wit-months-28',
    category: '재치',
    question: '28일이 있는 달은 1년에 몇 개?',
    choices: ['1개', '2개', '4개', '12개'],
    correctIndex: 3,
    note: '모든 달이 최소 28일은 있다.',
  },
  {
    id: 'wit-cotton-iron',
    category: '재치',
    question: '1kg의 솜과 1kg의 쇠, 더 무거운 것은?',
    choices: ['솜', '쇠', '똑같다', '알 수 없음'],
    correctIndex: 2,
    note: '둘 다 1kg.',
  },
  {
    id: 'wit-alphabet-letters',
    category: '재치',
    question: "'알파벳'에는 글자가 몇 개 들어 있을까?",
    choices: ['26개', '3개', '24개', '알 수 없음'],
    correctIndex: 1,
    note: "단어 '알·파·벳' 세 글자.",
  },
  {
    id: 'wit-right-hand',
    category: '재치',
    question: '오른손으로 절대 만질 수 없는 것은?',
    choices: ['왼손', '오른팔', '오른손', '오른발'],
    correctIndex: 2,
    note: '오른손은 자기 자신을 잡을 수 없다.',
  },
  {
    id: 'wit-race-overtake',
    category: '재치',
    question: '달리기에서 2등을 제치면 몇 등?',
    choices: ['1등', '2등', '3등', '꼴등'],
    correctIndex: 1,
    note: '제친 그 사람 자리(2등)를 차지할 뿐.',
  },
  {
    id: 'wit-candle-blow',
    category: '재치',
    question: '켜둔 양초 10개 중 3개가 바람에 꺼졌다. 다음 날 남은 건?',
    choices: ['7개', '10개', '3개', '0개'],
    correctIndex: 2,
    note: '꺼진 3개만 남고 나머지는 끝까지 타버린다.',
  },
  {
    id: 'wit-what-goes-up',
    category: '재치',
    question: '올라가기만 하고 절대 내려오지 않는 것은?',
    choices: ['연기', '나이', '풍선', '온도'],
    correctIndex: 1,
    note: '나이는 늘기만 한다.',
  },
  {
    id: 'wit-footprints',
    category: '재치',
    question: '가져갈수록 더 많이 남는 것은?',
    choices: ['돈', '발자국', '시간', '그림자'],
    correctIndex: 1,
    note: '걸을수록 발자국이 늘어난다.',
  },
  {
    id: 'wit-never-wither',
    category: '재치',
    question: '물을 주면 죽고, 안 주면 사는 것은?',
    choices: ['선인장', '조화', '불', '이끼'],
    correctIndex: 2,
    note: '불은 물에 꺼진다.',
  },
  {
    id: 'wit-sponge-holes',
    category: '재치',
    question: '구멍이 숭숭 뚫렸는데도 물을 머금는 것은?',
    choices: ['그물', '스펀지', '체', '빨대'],
    correctIndex: 1,
    note: '스펀지는 구멍이 많아도 물을 빨아들인다.',
  },
  {
    id: 'wit-birthday-twice',
    category: '재치',
    question: '한 해에 생일을 두 번 챙기는 사람도 있다. 어떻게?',
    choices: ['거짓말', '쌍둥이', '음력·양력', '윤년생'],
    correctIndex: 2,
    note: '음력 생일과 양력 생일을 둘 다 챙기면.',
  },

  // ── 전제 뒤집기 (구 상황추론 — 6초 안에 통하는 것만 존치) ─────────
  {
    id: 'logic-sheep-9',
    category: '재치',
    question: '양 17마리 중 9마리만 빼고 모두 죽었다. 남은 양은?',
    choices: ['8마리', '9마리', '17마리', '0마리'],
    correctIndex: 1,
    note: "'9마리만 빼고'이므로 그 9마리가 살아남았다.",
  },
  {
    id: 'logic-fire-first',
    category: '재치',
    question: '추운 방, 성냥 한 개비로 양초·난로·램프에 불을 붙이려면 뭐부터?',
    choices: ['양초', '난로', '성냥', '램프'],
    correctIndex: 2,
    note: '성냥에 먼저 불을 붙여야 나머지에 옮길 수 있다.',
  },
  {
    id: 'logic-green-house',
    category: '재치',
    question: '빨간 집은 빨간 벽돌, 노란 집은 노란 벽돌. 그린하우스는 뭘로 지을까?',
    choices: ['초록 벽돌', '유리', '잔디', '나무'],
    correctIndex: 1,
    note: '그린하우스 = 온실, 유리로 짓는다.',
  },
  {
    id: 'logic-dark-road',
    category: '재치',
    question: '불 꺼진 차가 검은 옷 입은 사람을 가로등도 없이 피했다. 어떻게?',
    choices: ['헤드라이트', '가로등', '대낮이라서', '달빛'],
    correctIndex: 2,
    note: '깜깜할 거란 건 착각 — 사실 환한 낮이었다.',
  },
  {
    id: 'logic-three-gen-apple',
    category: '재치',
    question: '두 아버지와 두 아들이 사과를 하나씩 나눴는데 3개면 충분했다. 왜?',
    choices: ['반씩 잘라서', '세 사람뿐이라서', '한 명이 양보', '사실 4개'],
    correctIndex: 1,
    note: '할아버지·아버지·아들 3대 = 아버지 2명·아들 2명.',
  },
  {
    id: 'logic-doctor-mother',
    category: '재치',
    question: '의사가 "저 환자는 내 아들"이라는데 의사는 그 아이의 아버지가 아니다. 누구?',
    choices: ['삼촌', '어머니', '새아빠', '형'],
    correctIndex: 1,
    note: '의사는 그 아이의 어머니.',
  },

  // ── 확장 풀 (큐레이션 통과분) ──────────────────────────────────
  {
    id: 'pun-a-thief-cat-gold',
    category: '말장난',
    question: '도둑고양이에게 어울리는 금은?',
    choices: ['백금', '야금야금', '순금', '현금'],
    correctIndex: 1,
    note: "몰래 조금씩 먹는 '야금야금'을 금 이름처럼 말장난.",
  },
  {
    id: 'pun-a-iron-food',
    category: '말장난',
    question: '다리미가 좋아하는 음식은?',
    choices: ['국수', '피자', '만두', '떡볶이'],
    correctIndex: 1,
    note: "옷을 쭉쭉 '펴-자'와 피자의 발음 말장난.",
  },
  {
    id: 'pun-a-titanic-boat',
    category: '말장난',
    question: '구명보트엔 몇 명 탈까?',
    choices: ['7명', '8명', '9명', '10명'],
    correctIndex: 2,
    note: "'구명'에 숫자 '9명'이 숨어 있는 말장난.",
  },
  {
    id: 'pun-a-cucumber-shock',
    category: '말장난',
    question: '오이가 깜짝 놀라면?',
    choices: ['오이무침', '오마이갓', '오이지', '오이소박이'],
    correctIndex: 1,
    note: "'오이'와 영어 'Oh my'를 엮은 발음 말장난.",
  },
  {
    id: 'pun-a-strawberry-greeting',
    category: '말장난',
    question: '딸기가 직장에서 받는 호칭은?',
    choices: ['딸기씨', '딸기님', '딸기양', '딸기군'],
    correctIndex: 0,
    note: "딸기 속 '씨(씨앗)'와 존칭 '씨'를 겹친 말장난.",
  },
  {
    id: 'pun-a-cow-money',
    category: '말장난',
    question: '소가 우는 곳은?',
    choices: ['우시장', '소시장', '축사', '외양간'],
    correctIndex: 0,
    note: "소 우는 '우'와 시장을 합친 '우시장' 말장난.",
  },
  {
    id: 'pun-a-radish-laugh',
    category: '말장난',
    question: '무가 크게 웃으면?',
    choices: ['무말랭이', '무하하', '무생채', '무김치'],
    correctIndex: 1,
    note: "'무'와 웃음소리 '하하'를 붙인 '무하하' 말장난.",
  },
  {
    id: 'pun-a-shrimp-back',
    category: '말장난',
    question: '새우가 다니는 병원 과는?',
    choices: ['내과', '정형외과', '안과', '치과'],
    correctIndex: 1,
    note: '등이 굽은 새우라 허리 펴러 가는 정형외과 말장난.',
  },
  {
    id: 'pun-a-bread-greeting',
    category: '말장난',
    question: '빵이 웃으면?',
    choices: ['빵긋', '빵빵', '빵점', '빵야'],
    correctIndex: 0,
    note: "활짝 웃는 '방긋'을 '빵긋'으로 바꾼 말장난.",
  },
  {
    id: 'pun-a-snake-fast',
    category: '말장난',
    question: '세상에서 가장 무거운 새는?',
    choices: ['독수리', '백조', '타조', '펭귄'],
    correctIndex: 1,
    note: "백조를 숫자 '100조'로 읽은 말장난.",
  },
  {
    id: 'pun-a-rabbit-fast',
    category: '말장난',
    question: '토끼가 좋아하는 대답은?',
    choices: ['깡총', '빨리나와', '당근이지', '토할것같아'],
    correctIndex: 2,
    note: "'당연하지'를 토끼가 좋아하는 '당근이지'로 바꾼 말장난.",
  },
  {
    id: 'pun-a-potato-shock',
    category: '말장난',
    question: '세상에서 가장 시끄러운 과일은?',
    choices: ['수박', '방울토마토', '참외', '자두'],
    correctIndex: 1,
    note: "딸랑딸랑 소리 나는 '방울'이 든 방울토마토.",
  },
  {
    id: 'pun-a-clam-quiet',
    category: '말장난',
    question: '가장 입이 무거운 동물은?',
    choices: ['조개', '문어', '거북', '오징어'],
    correctIndex: 0,
    note: "꽉 다문 조개껍데기를 '입이 무겁다'로 비튼 말장난.",
  },
  {
    id: 'pun-a-apple-apology',
    category: '말장난',
    question: '사과가 가장 잘하는 것은?',
    choices: ['사과', '변명', '칭찬', '질문'],
    correctIndex: 0,
    note: "과일 사과와 '미안하다 사과'의 동음이의 말장난.",
  },
  {
    id: 'pun-a-sheep-yes',
    category: '말장난',
    question: '바나나가 크게 웃으면?',
    choices: ['바나나킥', '바나나칩', '바나나맛', '바나나우유'],
    correctIndex: 0,
    note: "웃다가 '킥' 하는 소리를 바나나킥에 빗댄 말장난.",
  },
  {
    id: 'pun-a-horse-tea',
    category: '말장난',
    question: '말이 좋아하는 음료는?',
    choices: ['말차', '당근주스', '사이다', '우유'],
    correctIndex: 0,
    note: "동물 말과 '말차(가루녹차)'의 동음 말장난.",
  },
  {
    id: 'pun-a-deer-surprise',
    category: '말장난',
    question: '병아리가 가장 잘 먹는 약은?',
    choices: ['삐약', '소화제', '감기약', '비타민'],
    correctIndex: 0,
    note: "병아리 울음 '삐악'을 약에 빗댄 말장난.",
  },
  {
    id: 'pun-a-mouse-game',
    category: '말장난',
    question: '쥐가 잘하는 컴퓨터 작업은?',
    choices: ['클릭', '타이핑', '코딩', '출력'],
    correctIndex: 0,
    note: "동물 쥐와 컴퓨터 '마우스'를 엮은 말장난.",
  },
  {
    id: 'pun-a-melon-greeting',
    category: '말장난',
    question: '참외가 처음 만나서 하는 말은?',
    choices: ['반가외', '참외씨', '노랗네', '아삭해'],
    correctIndex: 0,
    note: "'반가워'를 참외풍으로 '반가외'라 한 말장난.",
  },
  {
    id: 'pun-b-baker-city',
    category: '말장난',
    question: '빵집 주인이 제일 무서워하는 도시는?',
    choices: ['로마', '뉴욕', '런던', '파리'],
    correctIndex: 3,
    note: "빵에 곤충 '파리'가 꼬이는 것과 도시 파리가 같은 말.",
  },
  {
    id: 'pun-b-nose-fruit',
    category: '말장난',
    question: '코가 제일 좋아하는 과일은?',
    choices: ['딸기', '수박', '코코넛', '참외'],
    correctIndex: 2,
    note: "'코'코넛 첫 글자에 코가 들어가서.",
  },
  {
    id: 'pun-b-eye-vegetable',
    category: '말장난',
    question: '눈이 여러 개 달린 채소는?',
    choices: ['감자', '당근', '양파', '오이'],
    correctIndex: 0,
    note: "감자의 싹 나는 자리를 '눈'이라 부르고 여러 개라서.",
  },
  {
    id: 'pun-b-pilot-food',
    category: '말장난',
    question: '조종사가 제일 좋아하는 생선은?',
    choices: ['갈치', '고등어', '날치', '참치'],
    correctIndex: 2,
    note: "하늘을 나는 조종사와 '날아오르는' 날치가 통해서.",
  },
  {
    id: 'pun-b-farmer-king',
    category: '말장난',
    question: '농부가 가장 존경하는 왕은?',
    choices: ['세종대왕', '파종대왕', '태종', '정조'],
    correctIndex: 1,
    note: "씨를 뿌리는 일 '파종'을 대왕 이름처럼 비튼 말.",
  },
  {
    id: 'pun-b-judge-drink',
    category: '말장난',
    question: '판사가 제일 좋아하는 음료는?',
    choices: ['콜라', '사이다', '환타', '식혜'],
    correctIndex: 1,
    note: "속이 시원한 '사이다'와 시원한 판결이 통해서.",
  },
  {
    id: 'pun-b-hand-animal',
    category: '말장난',
    question: '손이 제일 좋아하는 동물은?',
    choices: ['사자', '손오공', '악어', '사슴'],
    correctIndex: 1,
    note: "'손'오공 첫 글자에 손이 들어가서.",
  },
  {
    id: 'pun-b-knee-country',
    category: '말장난',
    question: '개가 학생을 가르치면?',
    choices: ['개인지도', '개훈련', '강아지반', '애견교실'],
    correctIndex: 0,
    note: "'개'와 '개인 지도'를 엮은 '개인지도' 말장난.",
  },
  {
    id: 'pun-b-clock-animal',
    category: '말장난',
    question: '시계가 제일 좋아하는 동물은?',
    choices: ['째깍이', '뻐꾸기', '독수리', '비둘기'],
    correctIndex: 1,
    note: '시간을 알리는 뻐꾸기시계가 있어서.',
  },
  {
    id: 'pun-b-banker-fruit',
    category: '말장난',
    question: '은행원이 제일 좋아하는 열매는?',
    choices: ['사과', '은행', '바나나', '감'],
    correctIndex: 1,
    note: '돈 다루는 은행과 은행나무 열매 은행이 같은 말.',
  },
  {
    id: 'pun-b-belly-fruit',
    category: '말장난',
    question: '배(신체)가 제일 좋아하는 과일은?',
    choices: ['사과', '배', '감', '귤'],
    correctIndex: 1,
    note: '신체 배와 과일 배가 같은 말.',
  },
  {
    id: 'pun-b-finger-snack',
    category: '재치',
    question: '손가락이 제일 좋아하는 과자는?',
    choices: ['빼빼로', '새우깡', '꼬깔콘', '홈런볼'],
    correctIndex: 2,
    note: '손가락 끝에 끼워 먹는 꼬깔콘이라서.',
  },
  {
    id: 'pun-c-coldest-sea',
    category: '말장난',
    question: '세상에서 가장 빠른 새는?',
    choices: ['눈깜짝할새', '제비', '총알새', '번개새'],
    correctIndex: 0,
    note: "'눈 깜짝할 새'에 '새'를 빗댄 말장난.",
  },
  {
    id: 'pun-c-boring-school',
    category: '말장난',
    question: '세상에서 가장 지루한 중학교는?',
    choices: ['로딩중', '대기중', '고민중', '수업중'],
    correctIndex: 0,
    note: "'로딩 중'의 '중'을 중학교로 빗댄 말.",
  },
  {
    id: 'pun-c-edible-swallow',
    category: '말장난',
    question: '사람이 먹을 수 있는 제비는?',
    choices: ['강남제비', '흥부제비', '수제비', '손제비'],
    correctIndex: 2,
    note: "손으로 떠 만든 '수제비'.",
  },
  {
    id: 'pun-c-king-fall',
    category: '말장난',
    question: '개 중에서 가장 아름다운 개는?',
    choices: ['진돗개', '무지개', '삽살개', '풍산개'],
    correctIndex: 1,
    note: "하늘의 '무지개'를 개에 빗댄 말장난.",
  },
  {
    id: 'pun-c-meat-dog',
    category: '말장난',
    question: '고기 먹을 때마다 따라다니는 개는?',
    choices: ['이쑤시개', '집게', '무지개', '번개'],
    correctIndex: 0,
    note: "이를 쑤시는 '이쑤시개'의 '개'.",
  },
  {
    id: 'pun-c-dirty-clean',
    category: '재치',
    question: '닦을수록 더 더러워지는 것은?',
    choices: ['거울', '유리창', '걸레', '수건'],
    correctIndex: 2,
    note: '때를 닦아내며 자기는 더러워지는 걸레.',
  },
  {
    id: 'pun-c-newspaper-door',
    category: '말장난',
    question: '아침마다 온 세상을 볼 수 있는 문은?',
    choices: ['대문', '신문', '창문', '정문'],
    correctIndex: 1,
    note: "세상 소식을 다 보는 '신문(門)'.",
  },
  {
    id: 'pun-c-candle-cry',
    category: '재치',
    question: '어두울 때 머리 풀고 눈물 흘리는 것은?',
    choices: ['양초', '전구', '손전등', '가로등'],
    correctIndex: 0,
    note: '심지를 풀고 촛농을 흘리는 양초.',
  },
  {
    id: 'pun-c-vacation-town',
    category: '말장난',
    question: '초등학생이 가장 좋아하는 동네는?',
    choices: ['방학동', '공부동', '시험동', '숙제동'],
    correctIndex: 0,
    note: "방학이 떠오르는 동네 이름 '방학동'.",
  },
  {
    id: 'pun-c-usedcar-student',
    category: '말장난',
    question: '중·고등학생이 타는 차는?',
    choices: ['새차', '외제차', '중고차', '경차'],
    correctIndex: 2,
    note: "중학생·고등학생을 줄여 '중고차'.",
  },
  {
    id: 'pun-c-dad-car',
    category: '말장난',
    question: '아빠한테 선물하기 좋은 차 이름은?',
    choices: ['소나타', '아반떼', '그랜저', '모닝'],
    correctIndex: 1,
    note: "'아빠한테~'와 발음이 비슷한 아반떼.",
  },
  {
    id: 'pun-c-crane-intro',
    category: '말장난',
    question: '학이 자기소개를 하면?',
    choices: ['입학', '방학', '전학', '휴학'],
    correctIndex: 2,
    note: "'전(저는) 학입니다' → 전학.",
  },
  {
    id: 'pun-c-hate-pyeon',
    category: '말장난',
    question: '편을 하기 싫은 것을 세 글자로?',
    choices: ['편식함', '편안함', '편가름', '편두통'],
    correctIndex: 1,
    note: "'편 안 함' → 편안함.",
  },
  {
    id: 'pun-c-cant-buy-apt',
    category: '말장난',
    question: '어른들은 못 사는 아파트는?',
    choices: ['아이파크', '래미안', '자이', '힐스테이트'],
    correctIndex: 0,
    note: "'아이(만) 파크' → 어른은 못 산다.",
  },
  {
    id: 'pun-c-cap-shoe',
    category: '말장난',
    question: '모자 사이에 신발을 두면?',
    choices: ['캡사이신', '모신발', '사이모자', '신모사'],
    correctIndex: 0,
    note: '캡(모자)+사이+신(신발) → 캡사이신.',
  },
  {
    id: 'pun-c-spy-bird',
    category: '말장난',
    question: '간첩이 동물원에서 찾는 새는?',
    choices: ['공작새', '독수리', '앵무새', '참새'],
    correctIndex: 0,
    note: "비밀 '공작'을 펴는 공작새.",
  },
  {
    id: 'pun-c-inedible-gam',
    category: '말장난',
    question: '감인데 먹을 수 없는 감은?',
    choices: ['홍시', '곶감', '영감', '단감'],
    correctIndex: 2,
    note: "나이 든 어르신 '영감'.",
  },
  {
    id: 'pun-c-mosaic-taekkyeon',
    category: '말장난',
    question: '엄마와 아들이 함께 택견을 하면?',
    choices: ['부자유친', '모자이크', '가족애', '합동기'],
    correctIndex: 1,
    note: "모자(母子)가 '이크!' 하면 모자이크.",
  },
  {
    id: 'pun-c-grape-laugh',
    category: '말장난',
    question: '세상에서 가장 빠른 떡은?',
    choices: ['찰떡', '헐레벌떡', '꿀떡', '인절미'],
    correctIndex: 1,
    note: "급히 서두르는 '헐레벌떡'에 떡을 빗댄 말장난.",
  },
  {
    id: 'pun-c-cry-vegetable',
    category: '말장난',
    question: '파가 부르르 떨며 화내면?',
    choices: ['양파탱', '파르르', '상추쌈', '열무침'],
    correctIndex: 1,
    note: "파가 '파르르' 떠는 말장난.",
  },
  {
    id: 'pun-c-money-soup',
    category: '말장난',
    question: '사람들이 가장 싫어하는 거리는?',
    choices: ['찻길', '걱정거리', '지름길', '골목길'],
    correctIndex: 1,
    note: "고민거리 '걱정거리'를 길(거리)처럼 비튼 말장난.",
  },
  {
    id: 'pun-c-fast-train-snack',
    category: '말장난',
    question: '기차가 가장 좋아하는 과자는?',
    choices: ['칙촉', '빼빼로', '쿠크다스', '에이스'],
    correctIndex: 0,
    note: "기차 소리 '칙칙'을 닮은 칙촉.",
  },
  {
    id: 'pun-c-sleepy-bug',
    category: '말장난',
    question: '가장 잠이 많은 곤충은?',
    choices: ['나비', '잠자리', '무당벌레', '사슴벌레'],
    correctIndex: 1,
    note: "이름에 '잠자리'가 들어간 잠자리.",
  },
  {
    id: 'pun-c-dragon-snack',
    category: '말장난',
    question: '용은 용인데 속이 텅 빈 용은?',
    choices: ['용왕', '이무기', '공룡', '용두사미'],
    correctIndex: 2,
    note: "공룡의 '공'을 빌 공(空)으로 읽은 말장난.",
  },
  {
    id: 'pun-c-honest-tree',
    category: '말장난',
    question: '가장 정직한 나무는?',
    choices: ['참나무', '거짓나무', '대나무', '소나무'],
    correctIndex: 0,
    note: "'참(진실)'이 들어간 참나무.",
  },
  {
    id: 'pun-c-flying-cat',
    category: '말장난',
    question: '하늘을 나는 고양이는?',
    choices: ['야옹비행', '나비', '날냥이', '공중묘'],
    correctIndex: 1,
    note: "고양이 별명 '나비'와 나는 나비를 겹친 말장난.",
  },
  {
    id: 'pun-c-angry-rice',
    category: '말장난',
    question: '밥이 화가 나면?',
    choices: ['볶음밥', '비빔밥', '주먹밥', '누룽지'],
    correctIndex: 2,
    note: "'주먹' 불끈 쥔 주먹밥.",
  },
  {
    id: 'pun-c-king-fish',
    category: '말장난',
    question: '바다에서 가장 등급 높은 생선은?',
    choices: ['고등어', '대왕문어', '임금생선', '왕고래'],
    correctIndex: 0,
    note: "높은 '고등(高等)'의 고등어 말장난.",
  },
  {
    id: 'pun-c-deepest-well',
    category: '말장난',
    question: '결정 못 하고 망설이는 우물은?',
    choices: ['옹달샘', '고민샘', '우물쭈물', '두레샘'],
    correctIndex: 2,
    note: "결정 못 하고 '우물쭈물'하는 우물.",
  },
  {
    id: 'wit-a-train-driver-age',
    category: '재치',
    question: '기차가 100km로 달린다. 운전사 나이는?',
    choices: ['100살', '40살', '당신 나이', '알 수 없음'],
    correctIndex: 2,
    note: "기차를 모는 '운전사'가 이 문제를 읽는 당신이라는 함정",
  },
  {
    id: 'wit-a-month-shortest',
    category: '말장난',
    question: '발음하면 이가 가장 시린 달은?',
    choices: ['1월', '11월', '12월', '2월'],
    correctIndex: 3,
    note: "2월은 '이~월'이라 이가 시리다, 말장난",
  },
  {
    id: 'wit-a-elevator-button',
    category: '재치',
    question: '10층 사람이 출근땐 1층, 퇴근땐 7층까지만 탄다. 왜?',
    choices: ['운동하려고', '키가 작아서', '고소공포증', '엘베 고장'],
    correctIndex: 1,
    note: '키가 작아 10층 버튼에 손이 안 닿고 7층까지만 누름',
  },
  {
    id: 'wit-a-word-spacing',
    category: '재치',
    question: "'아버지가방에들어가신다'에서 아버지는 어디로?",
    choices: ['가방 속', '방 안', '부엌', '마당'],
    correctIndex: 1,
    note: "'아버지가 방에 들어가신다'로 띄면 방, 띄어쓰기 함정",
  },
  {
    id: 'wit-a-clock-mirror',
    category: '재치',
    question: '거울에 비친 시계가 3시면 실제 시각은?',
    choices: ['3시', '9시', '6시', '12시'],
    correctIndex: 1,
    note: '거울은 좌우 반전, 3시의 거울상은 9시',
  },
  {
    id: 'wit-a-twins-birthday',
    category: '재치',
    question: '같은 부모, 같은 날 태어난 둘이 쌍둥이가 아니다. 왜?',
    choices: ['입양', '세쌍둥이', '나이차', '사촌'],
    correctIndex: 1,
    note: '셋 이상이면 쌍둥이 아닌 세쌍둥이 중 둘, 함정',
  },
  {
    id: 'wit-a-river-cross',
    category: '재치',
    question: '다리·배·헤엄 없이 강을 건너는 방법은?',
    choices: ['뛴다', '얼었을 때', '돌다리', '불가능'],
    correctIndex: 1,
    note: "강이 얼면 걸어서 건넘, '항상 물'이라는 전제 함정",
  },
  {
    id: 'wit-a-three-apples',
    category: '재치',
    question: '사과 5개 중 3개를 가져가면 내게 남는 건?',
    choices: ['2개', '3개', '5개', '0개'],
    correctIndex: 1,
    note: "'가져간' 3개가 곧 내가 가진 것, 관점 함정",
  },
  {
    id: 'wit-a-king-without-crown',
    category: '재치',
    question: '머리가 있는데 모자를 못 쓰는 것은?',
    choices: ['대머리', '압정', '사람', '왕'],
    correctIndex: 1,
    note: "압정·못은 '머리'가 있지만 모자를 못 씀, 신체 머리로 오인",
  },
  {
    id: 'wit-a-two-doors',
    category: '재치',
    question: '뜨면 열리고 감으면 닫히는 것은?',
    choices: ['창문', '책', '눈', '입'],
    correctIndex: 2,
    note: '눈을 뜨면 시야가 열리고 감으면 닫힘',
  },
  {
    id: 'wit-a-color-of-bear',
    category: '재치',
    question: '어느 쪽 1km 가도 남쪽뿐인 집의 곰 색은?',
    choices: ['갈색', '검정', '흰색', '회색'],
    correctIndex: 2,
    note: '그 조건은 북극, 북극곰은 흰색, 방향 트릭',
  },
  {
    id: 'wit-a-empty-pocket',
    category: '재치',
    question: '넣을수록 주머니가 가벼워지는 것은?',
    choices: ['돌', '구멍', '솜', '공기'],
    correctIndex: 1,
    note: '구멍을 넣을수록 천이 사라져 가벼워짐, 역설 함정',
  },
  {
    id: 'wit-a-shadow-run',
    category: '재치',
    question: '아무리 빨리 달려도 못 잡는 것은?',
    choices: ['바람', '내 그림자', '앞사람', '시간'],
    correctIndex: 1,
    note: '내 그림자는 늘 같은 거리로 따라와 영원히 못 잡음',
  },
  {
    id: 'wit-a-dry-rain',
    category: '재치',
    question: '비를 맞아도 더 젖지 않는 것은?',
    choices: ['우산', '바다', '비옷', '처마'],
    correctIndex: 1,
    note: '바다는 이미 물이라 더 젖을 게 없음, 관점 함정',
  },
  {
    id: 'wit-a-light-heavy',
    category: '재치',
    question: '낮엔 가볍고 밤엔 무거워지는 것은?',
    choices: ['가방', '눈꺼풀', '돌', '책'],
    correctIndex: 1,
    note: '밤엔 졸려 눈꺼풀이 천근만근, 비유 함정',
  },
  {
    id: 'wit-a-count-family',
    category: '재치',
    question: '형제 7명, 각자 여동생 1명씩. 형제자매는 모두 몇?',
    choices: ['14명', '8명', '16명', '9명'],
    correctIndex: 1,
    note: '여동생은 모두가 공유하는 한 명, 형제7+여동생1=8명',
  },
  {
    id: 'wit-a-no-weight-gold',
    category: '재치',
    question: '많이 가질수록 손해인 금은?',
    choices: ['순금', '벌금', '황금', '금괴'],
    correctIndex: 1,
    note: "벌금은 많을수록 손해, '금=귀함' 동음이의 트릭",
  },
  {
    id: 'wit-a-two-coins-110',
    category: '재치',
    question: '동전 둘 합 600원, 하나는 500원이 아니다. 무슨 동전?',
    choices: ['불가능', '100·100', '500·100', '50·550'],
    correctIndex: 2,
    note: "한 개'만' 500원 아니란 말, 나머지는 500원이라 500+100",
  },
  {
    id: 'wit-a-clean-dirty',
    category: '재치',
    question: '불은 불인데 뜨겁지 않은 불은?',
    choices: ['모닥불', '반딧불', '장작불', '화롯불'],
    correctIndex: 1,
    note: '스스로 빛을 내지만 뜨겁지 않은 반딧불.',
  },
  {
    id: 'wit-a-many-legs',
    category: '재치',
    question: '다리가 넷인데 못 걷는 것은?',
    choices: ['강아지', '책상', '말', '거북이'],
    correctIndex: 1,
    note: "책상은 다리 넷이지만 못 걸음, '다리=동물' 함정",
  },
  {
    id: 'logic-a-bar-water',
    category: '재치',
    question: '물 달라던 손님이 놀라자 고맙다며 갔다. 왜?',
    choices: ['딸꾹질이라', '물맛 없어서', '돈이 없어서', '장난쳐서'],
    correctIndex: 0,
    note: '딸꾹질엔 놀라게 하는 게 물보다 효과적.',
  },
  {
    id: 'logic-a-how-many-times-subtract',
    category: '재치',
    question: '30에서 6을 몇 번 뺄 수 있나?',
    choices: ['한 번', '다섯 번', '여섯 번', '무한히'],
    correctIndex: 0,
    note: '한 번 빼면 30이 아님, 매번 30에서 빼는 건 1회.',
  },
  {
    id: 'logic-a-survivors-bury',
    category: '재치',
    question: '비행기가 국경에 추락. 생존자는 어디 묻나?',
    choices: ['안 묻는다', '출발국에', '도착국에', '국경에'],
    correctIndex: 0,
    note: "'생존자'는 살아 있는 사람, 묻을 대상이 아님.",
  },
  {
    id: 'logic-a-rooster-egg',
    category: '재치',
    question: '지붕 꼭대기 수탉이 낳은 알은 어디로 굴러?',
    choices: ['알 못 낳음', '동쪽', '서쪽', '지붕 따라'],
    correctIndex: 0,
    note: '수탉은 알을 못 낳음, 굴러떨어질 알이 없음.',
  },
  {
    id: 'logic-a-socks-dark',
    category: '재치',
    question: '깜깜한데 검정·흰 양말서 같은 색 한 켤레, 최소?',
    choices: ['3짝', '2짝', '4짝', '10짝'],
    correctIndex: 0,
    note: '색 두 종류→3짝이면 반드시 같은 색 2짝(비둘기집).',
  },
  {
    id: 'logic-a-broken-watch',
    category: '재치',
    question: '멈춘 시계와 1분 느린 시계 중 더 자주 맞는 건?',
    choices: ['멈춘 시계', '느린 시계', '둘 다 같다', '항상 느린 것'],
    correctIndex: 0,
    note: '멈춘 시계는 하루 2번 정확, 느린 건 720일에 1번.',
  },
  {
    id: 'logic-a-train-smoke',
    category: '재치',
    question: '동쪽으로 달리는 전기기차의 연기는 어디로?',
    choices: ['연기 없음', '서쪽', '동쪽', '위쪽'],
    correctIndex: 0,
    note: '전기기차는 연기를 안 냄.',
  },
  {
    id: 'logic-a-ladder-tide',
    category: '재치',
    question: '배 사다리 10칸 중 3칸 잠김. 밀물 들면 몇 칸 더?',
    choices: ['더 안 잠김', '3칸', '5칸', '전부'],
    correctIndex: 0,
    note: '배가 물과 함께 떠올라 잠기는 칸 수 그대로.',
  },
  {
    id: 'mix-a-flower-city',
    category: '재치',
    question: '추울수록 키가 자라는 것은?',
    choices: ['고드름', '나무', '대나무', '얼음'],
    correctIndex: 0,
    note: '처마에서 얼며 점점 길어지는 고드름.',
  },
  {
    id: 'mix-a-black-heart',
    category: '말장난',
    question: '날마다 가슴에 흑심을 품은 것은?',
    choices: ['지우개', '연필', '자', '공책'],
    correctIndex: 1,
    note: '연필 속의 검은 심(흑심) 말장난.',
  },
  {
    id: 'mix-a-number-devil',
    category: '말장난',
    question: '악마의 반대를 숫자로 하면?',
    choices: ['6', '666', '1004', '777'],
    correctIndex: 2,
    note: "1004는 '천사'로 읽히는 숫자 말장난.",
  },
  {
    id: 'mix-a-cold-number',
    category: '말장난',
    question: '0을 부르는 다른 말은?',
    choices: ['빵', '구', '팔', '칠'],
    correctIndex: 0,
    note: "0을 '빵(영)'이라 읽는 말장난.",
  },
  {
    id: 'mix-a-clock-run',
    category: '재치',
    question: '하루 종일 달려도 제자리인 것은?',
    choices: ['자동차', '시계', '기차', '자전거'],
    correctIndex: 1,
    note: '시곗바늘은 돌고 돌아도 같은 자리.',
  },
  {
    id: 'mix-a-number-bread',
    category: '말장난',
    question: '병은 병인데 깨지지 않는 병은?',
    choices: ['꾀병', '유리병', '물병', '주스병'],
    correctIndex: 0,
    note: "아픈 척하는 '꾀병'은 깨지지 않는 병.",
  },
  {
    id: 'mix-a-fan-summer',
    category: '재치',
    question: '여름에 가장 고개를 많이 젓는 것은?',
    choices: ['에어컨', '선풍기', '부채', '냉장고'],
    correctIndex: 1,
    note: '좌우로 고개 돌리며 도는 선풍기.',
  },
  {
    id: 'mix-a-soap-thin',
    category: '재치',
    question: '씻을수록 야위어 가는 것은?',
    choices: ['수건', '비누', '칫솔', '빗'],
    correctIndex: 1,
    note: '쓸수록 작아지는 비누.',
  },
  {
    id: 'mix-a-number-eight',
    category: '재치',
    question: '옆으로 누우면 무한대가 되는 숫자는?',
    choices: ['6', '8', '3', '0'],
    correctIndex: 1,
    note: '8을 눕히면 무한대(∞) 기호가 된다.',
  },
  {
    id: 'pun-d-summer-drink',
    category: '말장난',
    question: '세종대왕이 만든 우유는?',
    choices: ['딸기우유', '아야어여 우유', '바나나우유', '초코우유'],
    correctIndex: 1,
    note: "한글 모음 '아야어여오요우유'를 활용한 말장난.",
  },
  {
    id: 'pun-d-uncle-job',
    category: '말장난',
    question: '엄마가 길을 잃으면?',
    choices: ['길치', '맘마미아', '마마보이', '미아'],
    correctIndex: 1,
    note: "엄마(mamma)와 'Mamma mia'를 엮은 말장난.",
  },
  {
    id: 'pun-d-cloud-bread',
    category: '말장난',
    question: '하늘이 굽는 빵은?',
    choices: ['구름빵', '식빵', '단팥빵', '크림빵'],
    correctIndex: 0,
    note: "하늘의 '구름'을 빵으로 본 합성어",
  },
  {
    id: 'pun-d-coffee-honest',
    category: '말장난',
    question: '오리를 생으로 먹으면?',
    choices: ['회오리', '오리탕', '훈제오리', '오리구이'],
    correctIndex: 0,
    note: "날것 '회(膾)'와 오리를 합친 '회오리' 말장난.",
  },
  {
    id: 'pun-d-spring-makeup',
    category: '말장난',
    question: '봄이 하는 화장은?',
    choices: ['꽃단장', '쌩얼', '떡칠', '민낯'],
    correctIndex: 0,
    note: "봄에 꽃으로 '꽃단장'",
  },
  {
    id: 'pun-d-teacher-fruit',
    category: '말장난',
    question: '선생님이 제일 좋아하는 과일은?',
    choices: ['참외', '사과', '수박', '바나나'],
    correctIndex: 0,
    note: "'참 잘했어요' 외친다는 참외",
  },
  {
    id: 'pun-d-cousin-tall',
    category: '말장난',
    question: '키가 제일 큰 친척은?',
    choices: ['큰아빠', '막내', '조카', '사촌'],
    correctIndex: 0,
    note: "호칭 '큰'을 키가 크다로",
  },
  {
    id: 'pun-d-fireman-veg',
    category: '재치',
    question: '화가 나면 새빨개지는 채소는?',
    choices: ['고추', '오이', '양배추', '깻잎'],
    correctIndex: 0,
    note: '매워서 빨갛게 익는 고추를 화에 빗댄 재치.',
  },
  {
    id: 'pun-d-proverb-bird',
    category: '말장난',
    question: '새가 가장 좋아하는 사자성어는?',
    choices: ['새옹지마', '천리길', '돌다리', '낮말'],
    correctIndex: 0,
    note: "'새옹지마'의 '새'를 새(鳥)로",
  },
  {
    id: 'pun-d-painter-color',
    category: '말장난',
    question: '밥은 밥인데 못 먹는 밥은?',
    choices: ['톱밥', '주먹밥', '볶음밥', '김밥'],
    correctIndex: 0,
    note: "톱질에서 나오는 '톱밥'은 먹을 수 없다.",
  },
  {
    id: 'pun-d-wind-instrument',
    category: '말장난',
    question: '바람이 잘 부는 악기는?',
    choices: ['휘파람', '드럼', '기타', '피아노'],
    correctIndex: 0,
    note: "입으로 부는 '휘파람'의 '파람'",
  },
  {
    id: 'wit-b-hot-dog',
    category: '말장난',
    question: '세상에서 가장 더운 개는?',
    choices: ['핫도그', '삽살개', '진돗개', '불개'],
    correctIndex: 0,
    note: 'hot dog를 더운 개로 직역',
  },
  {
    id: 'wit-b-laughing-flower',
    category: '재치',
    question: '분위기 좋을 때 활짝 피는 꽃은?',
    choices: ['웃음꽃', '해바라기', '나리꽃', '장미'],
    correctIndex: 0,
    note: "'웃음꽃'을 진짜 꽃처럼",
  },
  {
    id: 'wit-b-king-bread',
    category: '말장난',
    question: '세상에서 가장 슬픈 별은?',
    choices: ['샛별', '이별', '북극성', '별똥별'],
    correctIndex: 1,
    note: "헤어짐 '이별'을 별에 빗댄 말장난.",
  },
  {
    id: 'wit-b-angry-drink',
    category: '말장난',
    question: '화가 잔뜩 난 음료는?',
    choices: ['화채', '콜라', '사이다', '식혜'],
    correctIndex: 0,
    note: "'화'를 화남으로 읽은 화채",
  },
  {
    id: 'wit-b-thin-book',
    category: '말장난',
    question: '세상에서 가장 가난한 왕은?',
    choices: ['폭군', '최저임금', '대왕', '상감마마'],
    correctIndex: 1,
    note: "왕을 뜻하는 '임금'을 급여 '임금'으로 바꾼 말장난.",
  },
  {
    id: 'logic-b-broken-window',
    category: '말장난',
    question: '세상에서 가장 억울한 도형은?',
    choices: ['삼각형', '원', '사각형', '마름모'],
    correctIndex: 1,
    note: "'원통하다(억울하다)'의 원을 도형 원에 빗댄 말장난.",
  },
  {
    id: 'logic-b-two-doors',
    category: '말장난',
    question: '손으로 못 여는 문은?',
    choices: ['소문', '방문', '대문', '창문'],
    correctIndex: 0,
    note: "퍼지는 '소문'",
  },
  {
    id: 'logic-b-full-empty',
    category: '재치',
    question: '파낼수록 커지는 건?',
    choices: ['구덩이', '쓰레기', '빚', '나이'],
    correctIndex: 0,
    note: '흙을 버려 파낼수록 구덩이는 커짐',
  },
  {
    id: 'logic-b-silent-loud',
    category: '재치',
    question: '조용할수록 잘 들리는 건?',
    choices: ['심장소리', '음악', '침묵', '바람'],
    correctIndex: 0,
    note: '고요하면 자기 심장소리가 들림',
  },
  {
    id: 'logic-b-wet-while-drying',
    category: '재치',
    question: '말려주며 스스로 젖는 건?',
    choices: ['수건', '빨래', '머리', '햇빛'],
    correctIndex: 0,
    note: '몸 닦는 수건은 젖음',
  },
  {
    id: 'logic-b-house-no-door',
    category: '재치',
    question: '문도 창도 없는 집은?',
    choices: ['달팽이집', '오두막', '새집', '벌집'],
    correctIndex: 0,
    note: '등에 진 달팽이집',
  },
  {
    id: 'logic-b-catch-not-throw',
    category: '말장난',
    question: '차는 차인데 못 타는 차는?',
    choices: ['녹차', '기차', '버스', '자전거'],
    correctIndex: 0,
    note: "마시는 '녹차'는 탈 수 없는 차.",
  },
  {
    id: 'pun-e-palindrome-tomato',
    category: '말장난',
    question: '거꾸로 읽어도 똑같은 채소는?',
    choices: ['토마토', '오이', '당근', '배추'],
    correctIndex: 0,
    note: "'토마토'는 거꾸로 읽어도 토마토.",
  },
  {
    id: 'pun-e-palindrome-goose',
    category: '말장난',
    question: '거꾸로 읽어도 똑같은 새는?',
    choices: ['참새', '기러기', '제비', '까치'],
    correctIndex: 1,
    note: "'기러기'는 거꾸로 읽어도 기러기.",
  },
  {
    id: 'pun-e-palindrome-swiss',
    category: '말장난',
    question: '거꾸로 읽어도 똑같은 나라는?',
    choices: ['스위스', '스페인', '스웨덴', '프랑스'],
    correctIndex: 0,
    note: "'스위스'는 거꾸로 읽어도 스위스.",
  },
  {
    id: 'wit-c-toothpaste',
    category: '말장난',
    question: '약은 약인데 먹으면 안 되는 약은?',
    choices: ['감기약', '치약', '소화제', '영양제'],
    correctIndex: 1,
    note: '치약은 이를 닦는 것, 먹는 약이 아니다.',
  },

  // ── 검증 클래식 추가분 ─────────────────────────────────────────
  {
    id: 'pun-f-miso-opposite',
    category: '말장난',
    question: '미소의 반대말은?',
    choices: ['정색', '당기소', '화남', '무표정'],
    correctIndex: 1,
    note: '미시오(미소)의 반대는 당기시오(당기소).',
  },
  {
    id: 'pun-f-gentleman-intro',
    category: '말장난',
    question: '신사가 자기소개를 하면?',
    choices: ['신사임당', '신사도', '젠틀맨', '신사동'],
    correctIndex: 0,
    note: "'신사입니다' → 신사임당.",
  },
  {
    id: 'pun-f-uneatable-ricecake',
    category: '말장난',
    question: '떡은 떡인데 못 먹는 떡은?',
    choices: ['그림의떡', '개떡', '쑥떡', '꿀떡'],
    correctIndex: 0,
    note: '보기만 하는 그림의 떡.',
  },
  {
    id: 'pun-f-biggest-nose',
    category: '말장난',
    question: '세상에서 가장 큰 코는?',
    choices: ['코끼리코', '멕시코', '매부리코', '피노키오'],
    correctIndex: 1,
    note: "나라 이름 멕시'코' — 코 중에 제일 크다.",
  },
  {
    id: 'pun-f-elder-waterfall',
    category: '말장난',
    question: '나이 드신 분들이 좋아하는 폭포는?',
    choices: ['빅토리아', '나이아가라', '이구아수', '천지연'],
    correctIndex: 1,
    note: "'나이야 가라!' → 나이아가라.",
  },
  {
    id: 'pun-f-brave-mouse',
    category: '말장난',
    question: '고양이도 못 잡는 쥐는?',
    choices: ['생쥐', '박쥐', '다람쥐', '햄스터'],
    correctIndex: 1,
    note: '하늘을 나는 박쥐는 고양이가 못 잡는다.',
  },
  {
    id: 'pun-f-longest-food',
    category: '말장난',
    question: '세상에서 가장 긴 음식은?',
    choices: ['가래떡', '국수', '참기름', '대파'],
    correctIndex: 2,
    note: "'참 길음' → 참기름.",
  },
  {
    id: 'pun-f-santa-noodle',
    category: '말장난',
    question: '산타가 싫어하는 면 요리는?',
    choices: ['짜장면', '울면', '냉면', '라면'],
    correctIndex: 1,
    note: '우는 아이에겐 선물을 안 주니까 울면.',
  },
  {
    id: 'pun-f-sour-teeth-place',
    category: '말장난',
    question: '이상한 사람들이 모이는 곳은?',
    choices: ['미용실', '치과', '약국', '목욕탕'],
    correctIndex: 1,
    note: "'이(가) 상한' 사람들이 가는 치과.",
  },
  {
    id: 'pun-f-king-grumble',
    category: '말장난',
    question: '왕이 궁에 못 들어가고 하는 말은?',
    choices: ['궁금하다', '궁시렁궁시렁', '문 열어라', '환궁이요'],
    correctIndex: 1,
    note: "궁 밖에서 '궁시렁궁시렁'.",
  },
];

// id 사전순 정렬 — 추출 결정성을 풀의 삽입 순서와 분리한다(trivia와 동일 규약).
export const NONSENSE_POOL_SORTED: readonly NonsenseQuestion[] = [...NONSENSE_POOL].sort((a, b) =>
  a.id < b.id ? -1 : a.id > b.id ? 1 : 0,
);
